### ISSUE TITLE
can it be made to support custom DNS?

### ISSUE THREAD

**Issue by Nirose** [IngoZenz/personaldnsfilter#1]
having the ability have custom DNS when VPN server is active would be nice.

**Comment by IngoZenz** [comment]
it is in ...

just check dnsfilter.conf in the personaldnsfilter folder 

 


# detectDNS = true|false.
# if true, the DNS servers will be detected if possible.
# if false, the DNS Servers will be taken from the fallbackDNS setting below.
detectDNS = true

# fallbackDNS - list of DNS servers seperated by ";".
# Used in case DNS servers are not detected automatically (either switched off or not possible).
# The Google DNS Servers as default below:
fallbackDNS =  8.8.8.8; 8.8.4.4
 



you should set detectDNS= false and configure your custom DNS in the fallbackDNS setting

 


Gesendet: Mittwoch, 18. April 2018 um 10:29 Uhr
Von: "Niroj Manandhar" <notifications@github.com>
An: IngoZenz/personaldnsfilter <personaldnsfilter@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [IngoZenz/personaldnsfilter] can it be made to support custom DNS? (#1)


having the ability have custom DNS when VPN server is active would be nice.

**Comment by Nirose** [comment]
Thanks! that worked great.
