### ISSUE TITLE
Firewall integration

### ISSUE THREAD

**Issue by Amaterasu121** [IngoZenz/personaldnsfilter#10]
A firewall would be a nice accompaniment to adblocking. One that allows us to block a given app from connecting to the internet via mobile data, wifi or both. It would obviate using a separate firewall app that utilizes local vpn to function. 
The main object of this feature, imo, is to have an even better control over the connectivity of apps than what pdf gives us right now.

**Comment by d-adi4** [comment]
> A firewall would be a nice accompaniment to adblocking. One that allows us to block a given app from connecting to the internet via mobile data, wifi or both. It would obviate using a separate firewall app that utilizes local vpn to function.
> The main object of this feature, imo, is to have an even better control over the connectivity of apps than what pdf gives us right now.

It seems good cause when we whitelist app in PDF then we can block whole Internet from there too.. Nice..

**Comment by IngoZenz** [comment]
there could be the option to block everything  and only having the whitelisted apps bypassing the blocker.
However a full featured firewall is much more and it is out of scope for pDNSf.

**Comment by d-adi4** [comment]
That's would do the work.. No need to put separate switch for mobile data and WiFi.. And it'll keep app lightweight too..
Just one click either app will get full internet or no internet at all..
And for thanking you, I can't donate money cause I'm still a student but I've plenty of Internet.. I can be a tester for all your future release and with plenty of Internet I will test your app at its full potential.. And will also serve ad blocking hosts community by enlisting malicious links

Sincerely

PS: sorry for bad English

**Comment by Amaterasu121** [comment]
@IngoZenz Thanks. Just the ability to cut off their connection is good enough.
Would be great if this could be considered.

**Comment by IngoZenz** [comment]
if you want to do this, you could add a filter with all possible top level domains and thus everything would be blocked.
In order to allow an app you could whitelist it.
With this you'll get "Just one click either app will get full internet or no internet at all.." 
I am closing this issue.
