### ISSUE TITLE
problem with your custom openvpn

### ISSUE THREAD

**Issue by awalo666** [IngoZenz/personaldnsfilter#102]
Hello! I installed your fork of openvpn for android and it was ok. But for some reason i uninstall it to retry the most recent real openvpn for android. And when i try to install it its tell me that i can't because somebody have installed another version not compatible. But now i have no openvpn for android on my phone.

**Comment by IngoZenz** [comment]
Make sure you really uninstalled openVPN for pdnsf before installing the original

**Comment by awalo666** [comment]
He is already uninstall and i can't doing it again because he is not there. I will reinstall your fork and uninstall it again maybe it will work. I will try that when i got time and give you feedback

**Comment by IngoZenz** [comment]
I fear the issue is not caused by my fork in special...maybe something went wrong with uninstallation.
A reboot might also help...
Good luck!

**Comment by IngoZenz** [comment]
is this solved for you?

**Comment by awalo666** [comment]
Yes it his sorry
openvpn was uninstall in the phone but it was in the secure folder of my samsung device and that why

**Comment by IngoZenz** [comment]
Ok - so we can close this :-)
