### ISSUE TITLE
Having issue with configuring DOT on android

### ISSUE THREAD

**Issue by portiktamas** [IngoZenz/personaldnsfilter#105]
Hi, i configured my phone to use personaldnsfilter for more than a year now, and i found out that DOT is more secure than just plaintext dns resolvers. I wanted to use this feature in the app, but it isn't working. I'm pretty sure that https://www.nic.cz/odvr/ has a DOT resolver, but it doesn't work in the app. Am i missing out something?

**Comment by IngoZenz** [comment]
It is working for me... You need to use this string:
`193.17.47.1::853::DoT::odvr.nic.cz`

![image](https://user-images.githubusercontent.com/11963504/90288016-451a9300-de79-11ea-84c8-ae7a451a1b46.png)

**Comment by portiktamas** [comment]
Thank you! Now works great :)
