### ISSUE TITLE
not work correctly with "github.com" ???

### ISSUE THREAD

**Issue by hkl33** [IngoZenz/personaldnsfilter#108]
first of all, this is a gooood works! especially for people in those China, Iran....
but I had met some bugs at this way:

I set up a hosts file like: https://cdn.jsdelivr.net/gh/hkl33/ohmyzsh/tools/2.txt
and use it as filter to implement domain-hosts-file function on personalDnsfilter, but I have result of "github.com" by "127.0.0.1", and "bing.com" works well

![image](https://user-images.githubusercontent.com/69077082/92887482-1b886380-f447-11ea-9cb6-1204dcfb54c9.png)

**Comment by IngoZenz** [comment]
The only reason is that github.com is in your filters.

What filters are you using?
