### ISSUE TITLE
Always ON VPN using API

### ISSUE THREAD

**Issue by compliment** [IngoZenz/personaldnsfilter#11]
I know that it's there already, for some reason it maybe draining battery for me.
 I was wondering if you would like to implement it via API.

[android.com/reference](https://developer.android.com/reference/android/net/VpnService.html#SERVICE_META_DATA_SUPPORTS_ALWAYS_ON)
Cheers.

**Comment by IngoZenz** [comment]
Integrating with the VPN  Allways On feature of Android API level>= 24 makes sense.
I will check this ...
Battery drain shouldn`t be an issue with pDNSf...

**Comment by IngoZenz** [comment]
As far as I could see this is not possible for "fake" VPNs as pDNSf.
When enabling Autostart for pDNSf, it will be "allways on"... so there shouldn't be a functional issue.
I am closing this issue.
