### ISSUE TITLE
Option to pause filtering for x seconds or minutes

### ISSUE THREAD

**Issue by BlackDex** [IngoZenz/personaldnsfilter#114]
I have some apps which do not want to start/continue when having the filter active, but do continue to work if i disable it, start the app, and enable it again. In the logs i see that it does block the subsequent request so it is helping at least after the app is started.

To make this a bit easier it would be nice if there could be an option to have filtering paused for like 30 seconds or 1 minute (maybe even configurable and multiple options) so that i can just pause the filter for that x amount of time, start the app, and it will go and filter stuff afterwards again automatically.

Something like this is for example included in PiHole, which comes in handy sometimes.

**Comment by IngoZenz** [comment]
we have in version 1.50.46 now the option to pause from the notification ... Maybe this helps already...
The requirement with the timer is a bit to special - sorry ;-)
