### ISSUE TITLE
Problem of vpn considered as metered connection

### ISSUE THREAD

**Issue by boistordu** [IngoZenz/personaldnsfilter#116]
Hi,
Since you didn't activate issue on your fork from openvpn I'm obliged to write here. 

[Here](https://github.com/schwabe/ics-openvpn/issues/1247) is all the detail and the link to the problem 
Apparently the owner is saying that the fix is already done. So could you rebuild your app?

**Comment by IngoZenz** [comment]
Ok - Thanks... will have a look once I have some time ...

**Comment by IngoZenz** [comment]
[Uploading OpenVPNforPDNSF.zip…]()
Please gibt feedback if this is ok - based on latest origin ...

**Comment by IngoZenz** [comment]
[OpenVPNforPDNSF.zip](https://github.com/IngoZenz/personaldnsfilter/files/5342255/OpenVPNforPDNSF.zip)

**Comment by boistordu** [comment]
No still the same result. 
Version 0.7.14?

**Comment by IngoZenz** [comment]
sorry - I attached the wrong thing - please try again
[main-ui-universal-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/5345923/main-ui-universal-release.zip)

**Comment by boistordu** [comment]
Okey so now there is a problem of negotiating the ciphers between the server and the client. Since the old version was working 2 minutes ago I guess that it is because of the change

**Comment by IngoZenz** [comment]
Please try with the original arne version - I assume your issue is from there...

**Comment by IngoZenz** [comment]
just tried - it is the same ... guess you need to add BF-CBC as Encryption algorithm

**Comment by boistordu** [comment]
Give me a couple of days because I can't get hold of my vpn config files anymore

**Comment by IngoZenz** [comment]
new version based on openvpn 07.21 was released

**Comment by syrkuit** [comment]
In which version is this supposed to be fixed? The latest version (1.50.46.0) from Google Play still behaves in this debilitating way.

**Comment by IngoZenz** [comment]
Maybe a misunderstanding. This issue was about a bug in openVPN for Android and NOT personalDNSfilter. 
https://github.com/schwabe/ics-openvpn/issues/1247.
The bug was fixed in upstream and I have pulled it to my openVPN for pDNSf fork...

**Comment by syrkuit** [comment]
Hm, could be, and I'm now confused.

I'm using pDNSf, and the VPN it creates shows up as a metered connection which is causing various issues. Am I using the wrong apk or something?

**Comment by IngoZenz** [comment]
This thread is about openVPN and not personalDNSfilter app and it was fixed for openVPN.
Similar issue might be in personalDNSfilter - you might create a new issue for that and I'll check...
