### ISSUE TITLE
fdroid

### ISSUE THREAD

**Issue by M1Aston** [IngoZenz/personaldnsfilter#117]
It seems f-droid updates take a long time (to be released). It that option still working\available?
Thanks.

**Comment by IngoZenz** [comment]
Sure - it is still supported...

...there is currenly an issue with the android build... will have to check ...

 
 

Gesendet: Sonntag, 11. Oktober 2020 um 15:57 Uhr
Von: "M1Aston" <notifications@github.com>
An: "IngoZenz/personaldnsfilter" <personaldnsfilter@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [IngoZenz/personaldnsfilter] fdroid (#117)


 

It seems f-droid updates take a long time (to be released). It that option still working\available?
Thanks.

**Comment by IngoZenz** [comment]
f-droid is updated

**Comment by M1Aston** [comment]
Yes, I had already installed it. :-)
Thank you very much for the quick update. It's working well.
