### ISSUE TITLE
1.50.43.0: DoH works, but DoT throws IO Error

### ISSUE THREAD

**Issue by opusforlife2** [IngoZenz/personaldnsfilter#119]
I tried several different DoT entries. It keeps trying to reconnect to the same one over and over, and then reaches the default parallel connection limit of 100.

In earlier versions, if it encountered an error, it used to try the next one in the list.

Now it says: " Selected DNS: (-1ms) [same failed DoT entry here] ", and this line keeps repeating in the log every half a minute or so.

As an experiment, I tried a DoH entry, and it worked on the first try.

**Comment by IngoZenz** [comment]
The DNS Server is selected based on response time.

In your case it seems none of the configured DNS server works...

Can you send the dnsfilter.conf and dnsperf.info file for the non working case?

**Comment by IngoZenz** [comment]
is this issue still present?

**Comment by opusforlife2** [comment]
Sorry, I haven't had access to the device in question. When I get the chance, I'll send you the files you've asked for above.

**Comment by opusforlife2** [comment]
Okay, I played around with the config a little on my own device, and found that the app starts working again if I comment out the `routeIPs` parameter.

**Comment by opusforlife2** [comment]
Well, either that parameter was causing issues, or something else that I was unable to diagnose. Regardless, I haven't faced the issue on multiple devices for a couple of versions, so I'm closing this for lack of information.
