### ISSUE TITLE
[Feature Request] Additional default filters

### ISSUE THREAD

**Issue by esmoak** [IngoZenz/personaldnsfilter#12]
Please consider adding some of the Energized filters as default options to select in the app. They are very comprehensive.

https://github.com/AdroitAdorKhan/Energized/blob/master/README.md

**Comment by IngoZenz** [comment]
Ok - let me check this.
I think we'll need additional grouping of the filter option in order to keep this clear with the increasing number of filter options...

**Comment by philip707** [comment]
just signed github only to Thanking you, very useful tiny app

**Comment by esmoak** [comment]
I checked out the new filters and I like the setup. Thank you.

Not sure if I should close this issue or wait until change hits the main release. 

Thanks.

**Comment by IngoZenz** [comment]
as you wish. I could also close it once a new release is out

**Comment by philip707** [comment]
Sir, is it possible to exclude from recent apps and appeared in notification pull down menu,
Thank you

**Comment by IngoZenz** [comment]
@philip707  This issue is regardind default filters. Feel free to open an own issue for your concern.

**Comment by IngoZenz** [comment]
done with version 1.50.29
