### ISSUE TITLE
Query on DNS Server Configuration list

### ISSUE THREAD

**Issue by Moxville** [IngoZenz/personaldnsfilter#123]
Hi,
Thanks for this nice and simple application. 
I'm no techie. Just a layman. I have few queries. 

Today I downloaded the App from Play Store and when I checked 'dns server configuration' I see list of 8 DNS servers added
Queries:
1. How to find out which dns server the App is configured by default for name resolution ?

2. I see new Adguard dns servers in official site. Does it need to be changed ?
https://adguard.com/en/blog/adguard-dns-new-addresses.html

3. Is it possible to edit and save 'dns server configuration' to change the default DNS ? 
I want to add only Adguard DOH server (make it default) and remove all others DNS servers from the list
Adguard DOH Server
https://dns-family.adguard.com/dns-query

Sorry. I'm not using Telegram app (to ask any queries for support)

Thanks

**Comment by IngoZenz** [comment]
Hi,

 

1. by default the app uses the dns server of your provider.

In case this is disbaled, it will take the dns servers from the list you see when toching the dns field.

 

2. Yes - Thanks for the reminder :-)

 

3. Yes you can, make sure you add it in the needed format.

 

Nice day!

 
 

Gesendet: Montag, 16. November 2020 um 14:41 Uhr
Von: "Moxville" <notifications@github.com>
An: "IngoZenz/personaldnsfilter" <personaldnsfilter@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [IngoZenz/personaldnsfilter] Query on DNS Server Configuration list (#123)


 

Hi,
Thanks for this nice and simple application.
I'm no techie. Just a layman. I have few queries.

Today I downloaded the App from Play Store and when I checked 'dns server configuration' I see list of 8 DNS servers added
Queries:


	
	How to find out which dns server the App is configured by default for name resolution ?
	
	
	I see new Adguard dns servers in official site. Does it need to be changed ?
	https://adguard.com/en/blog/adguard-dns-new-addresses.html
	
	
	Is it possible to edit and save 'dns server configuration' to change the default DNS ?
	I want to add only Adguard DOH server (make it default) and remove all others DNS servers from the list
	Adguard DOH Server
	https://dns-family.adguard.com/dns-query
	


Sorry. I'm not using Telegram app (to ask any queries for support)

Thanks

**Comment by IngoZenz** [comment]
Seems this is solved - so closing...
