### ISSUE TITLE
Show app in the log.

### ISSUE THREAD

**Issue by anton-sutopo** [IngoZenz/personaldnsfilter#125]
Hi all,
Is it possible to know app that connect to a site?
 Thank you
.

**Comment by IngoZenz** [comment]
No, unfortunately Android does not offer an API for this.

**Comment by anton-sutopo** [comment]
Thank you for the answer. Just curious how personalDNSfilter can whitelist the request by app?

**Comment by IngoZenz** [comment]
For this there is an Android API within the Android VPNService Builder Interface

**Comment by anton-sutopo** [comment]
Ah.. Thank you.
