### ISSUE TITLE
SSL problem on older Android

### ISSUE THREAD

**Issue by nonchalantei** [IngoZenz/personaldnsfilter#129]
I got this message, sometimes the filter could still working but not today, no luck whatsoever, android 4.4 (sorry it's lame). thank you

DNS Filter: Reloading hosts filter ...
Aquired WIFI lock and partial wake lock!
ERROR loading filter: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
Released WIFI lock and partial wake lock!
Cannot update hosts filter file!
javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x62cfedc0: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x5d1a16fd:0x00000000)

**Comment by IngoZenz** [comment]
it is related to outdated trust store on old phones. They do not trust the new CAs and thus SSL fails.
Not sure if it is possible to update the trust store on non rooted phones.

**Comment by nonchalantei** [comment]
somehow the blocking is working now.
so are you trying to say that there's a workaround for rooted 4.4?

**Comment by IngoZenz** [comment]
I think on rooted devices you have more options to update the device - including trust store...
As a workarround you might disable the filter sources with problems and switch to other filter providers...

**Comment by nonchalantei** [comment]
ok thank you
