### ISSUE TITLE
Feature request: domain level blocks

### ISSUE THREAD

**Issue by ckuethe** [IngoZenz/personaldnsfilter#13]
It would be great to be able to block entire subdomains, domains, or even TLDs, eg.

- this.bad.example.com, that.bad.example.com, another.bad.example.com -> `bad.example.com`
- if I'm a dog on the internet, maybe I want to block all of `.cat`

**Comment by IngoZenz** [comment]
it is like that already.
An entry "bad.example.com" blocks also "*.bad.example.com"
