### ISSUE TITLE
Stuck in a loop of choosing the same unavailable DNS

### ISSUE THREAD

**Issue by ofiala-a51** [IngoZenz/personaldnsfilter#136]
This should speak for itself:
```
Selected DNS: (-1 ms) [94.140.14.140]::53::UDP
Selected DNS: (-1 ms) [94.140.14.140]::53::UDP
No DNS response from /94.140.14.140:53
IO Error occured! Check network or DNS config!
DNS filter: Reloading hosts filter ...
Acquired WIFI lock and partial wake lock!
Selected DNS: (-1 ms) [94.140.14.140]::53::UDP
ERROR loading filter: https://block.energized.pro/extensions/xtreme/formats/hosts
Released WIFI lock and partial wake lock!
Cannot update hosts filter file!
java.net.UnknownHostException: Unable to resolve host "block.energized.pro": No address associated with hostname
Retry at: Sun Jan 17 02:02:06 GMT+01:00 2021
DNS filter: Next filter reload:Sun Jan 17 02:02:06 GMT+01:00 2021
Selected DNS: (-1ms) [94.140.14.140]::53::UDP
```
My guess is that it interprets some kind of error value as a regular ping value and since the error value is distinguished from real values by being negative, it gets selected as the "fastest DNS" as it's smaller than all others.

**Comment by IngoZenz** [comment]
Actually it means that it did not find any valid DNS Server.

Is your network available? Check your DNS Server list.

If issue persists, please provide the file dnsperf.info from the personaldnsfilter folder

**Comment by IngoZenz** [comment]
please reopen this tikcet and provide dnsperf.info file in case issue persists...
