### ISSUE TITLE
VPN is considered a metered connection

### ISSUE THREAD

**Issue by syrkuit** [IngoZenz/personaldnsfilter#137]
With pDNSf 1.50.46.0 on Android 11, the created VPN shows up as a metered connection which is causing various issues. 

I don't think the was the case previously.

**Comment by IngoZenz** [comment]
It is fixed and will go into next release

**Comment by syrkuit** [comment]
Looking at the fix, I'm guessing it's not possible for the VPN state to match that of the underlying network?

Either choice comes with its own problems.. well behaved apps will take that setting into account before doing large data syncs in the background and so on.
If the VPN is set to metered, then these never happen.
If the VPN is set to unmetered, then these will happen when they shouldn't, and overload slower mobile connections or rack up charges on a network that's actually metered.

**Comment by IngoZenz** [comment]
According to the android API Docu, the fix should work in the way, that it takes the information from the underlying network which would be the correct behaviour. I hope it will work this way :-)

**Comment by syrkuit** [comment]
Nice, thanks for the quick turn around! I'll comment back if it doesn't look like it's working as it should but I'm not sure there'll be much you can do then.

**Comment by IngoZenz** [comment]
Feel free to try the fix from dev (should be stable)
[DNSFilter-1.5047-dev-0.zip](https://github.com/IngoZenz/personaldnsfilter/files/5834815/DNSFilter-1.5047-dev-0.zip)
