### ISSUE TITLE
Does not filter when Network connection turned off over night 

### ISSUE THREAD

**Issue by Meldario** [IngoZenz/personaldnsfilter#139]
Hello,
first of all, absolutely great work, I love your app!

When I go to sleep, I turn off Wi-Fi and mobile internet connection.
After activating Wi-Fi next day, filter doesn't work anymore. I have to restart Personaldnsfilter. 

When Network connections are turned off for a shot time, no problem. After getting internet again, app works. 

I hope, you can fix it :-) 

Greetings from Germany, 
Alex

**Comment by IngoZenz** [comment]
Should not be the case.

Are you running in default mode with local vpn? Or any other mode (proxy mode with / without root)

What is the output in the live log when it is not working ?

**Comment by Meldario** [comment]
Hello,
I use no ROOT Mode:
![grafik](https://user-images.githubusercontent.com/75611145/105692379-a3ef3880-5efe-11eb-99bf-030c21ec5981.png)
When I open DNSFilter in the Morning and enable WiFi, nothing is showen in the Log (only old requests).
App does not Filter.
Then I restart the App via InAppButton, it works.

Today, first of all I opend DNSfilter, made a Restart in App and enabled WiFi.
It connects and Log shows correct Filtering.

**Comment by IngoZenz** [comment]
Looks like as if your phone drops the VPN ...
Can you enable always-on VPN for personalDNSfilter within teh VPN settings of your phone? That should fix the issue...

**Comment by Meldario** [comment]
OK, I give it a try and will report, if it works or not. Thanks!

**Comment by Meldario** [comment]
Hi, I tried it a few times. "always-on" is enabled.
It doesn't work, I have to restart PersonalDNSfilter every morning. After that I can enable WiFi or MobileData.
Otherwise it doesn't block.
I made a Factory-Reset of my device, same Problem.
Hhhmmm, it is OK for me to restart the App, but would be great if I don't have to :-)
Any Ideas?
Greetings!

**Comment by IngoZenz** [comment]
Very strange - this is an exceptional case. Maybe you would like this issue in our Telegram Group?
https://telegram.me/pdnsf.
It might be related to Battery Optimization - you should disable this for pdnsf if not done already.
Is the VPN key Icon still visible (on top of the screen)  in the morning? It looks like as if you phone kills the VPN.

**Comment by Meldario** [comment]
I don`t know why, but it works since an Month without any Problems. Hhhmm strange...
