### ISSUE TITLE
Feature request: configurable log window

### ISSUE THREAD

**Issue by ckuethe** [IngoZenz/personaldnsfilter#14]
I love that I can see what queries are allowed and denied; one thing I'd like to see in the app is a way to filter out all the dns detection, ipv6, connectivity junk... That would greatly assist in figuring out what local changes I want to make.

**Comment by IngoZenz** [comment]
I might remove these logs in a future release...

**Comment by IngoZenz** [comment]
done with version 1.50.29

**Comment by ckuethe** [comment]
Looks great, thanks!

**Comment by esmoak** [comment]
I'm on 1.50.29 from F-Droid and am not seeing this option. Any tips? Looked through all advanced settings.

Thanks.

**Comment by IngoZenz** [comment]
On F-Droid there is still version 1.50.28 - you might ask there when they will have the new version (should be pulled automatically by F-droid)

**Comment by IngoZenz** [comment]
just saw it is v 1.50.29 now...
For changing logging options you need to edit the dnsfilter.conf file manually and set
 debug = true

**Comment by esmoak** [comment]
Thanks. I was looking at that option setting debug=true before I posted but I didn't change it yet.

I didn't see the difference in the scrolling log or the traffic_log file when upgrading to the new version with debug=false as default.

I'll look more closely and toggle the option to true later.

Thanks.

**Comment by IngoZenz** [comment]
with debug = false, you should see much less log output in the scrolling log - mainly the green and red hosts only plus initialization and network errors.
There is no impact to the trafficlog
