### ISSUE TITLE
feature-request: Integrating dnscrypt-proxy ?

### ISSUE THREAD

**Issue by zcattacz** [IngoZenz/personaldnsfilter#140]
https://github.com/DNSCrypt/dnscrypt-proxy provides arm binary for android but launching it is a fuss, and changing DNS setting requires root. It handles more upstream DNS protocol, I think it might be a good power-up for personaldnsfilter, if personaldnsfilter can provide a dedicate option to toggle its use (e.g. fork/kill the process, set/unset it as upstream server).

**Comment by IngoZenz** [comment]
Please check if following settings within dnsfilter.conf will do the job for you:

 


# manageDNSCryptProxy - Only for Android version
# if true, an installed DNScryptProxy will be started and stopped together with DNSFilter (requires root!)
manageDNSCryptProxy = false

# options for starting DNSCryptProxy
dnsCryptProxyStartOptions = -config /system/etc/dnscrypt-proxy/dnscrypt-proxy.toml

**Comment by zcattacz** [comment]
Hi, @IngoZenz thanks for the response. Sorry didn't noticed that earlier.
    
    # if true, an installed DNScryptProxy will be started and stopped together with DNSFilter (requires root!)
    
Not sure why it would require root. Can I use a intermediate port is >1024, plus a non-system config path ?
