### ISSUE TITLE
Use package-specific cache and data to avoid requiring STORAGE permissions

### ISSUE THREAD

**Issue by cobratbq** [IngoZenz/personaldnsfilter#144]
Would you consider making the `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` [required only for old Android versions](https://developer.android.com/guide/topics/manifest/uses-permission-element#maxSdk) in order to reduce unnecessary permissions for the app?

Android has marked mentioned permissions as dangerous. It seems that _personalDNSfilter_ uses only very reasonable storage requirements that are also fulfilled with `getExternalFilesDir` and `getExternalCacheDir`, and the mentioned permission is only relevant on [Android versions prior to 4.4 (KITKAT)](https://developer.android.com/reference/android/os/Build.VERSION_CODES#KITKAT).

**Comment by IngoZenz** [comment]
READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE is still needed for older Android versions.
With https://github.com/IngoZenz/personaldnsfilter/releases/tag/1.50.48.0, the config is now migrated to external app folder, so  Android will not need and ask for storage permissions anymore...
