### ISSUE TITLE
OneDrive Sync not working

### ISSUE THREAD

**Issue by onlytanmoy** [IngoZenz/personaldnsfilter#145]
Hiya, please see below image, OneDrive says 'can't sync while connected to a mobile hotspot' even though I am not. I get the same error even if I whitelist OneDrive in pDNSf. Pausing the pDNSf app also doesn't work.
The only way the sync works for me is to close the pDNSf app via the Close button. Any solution please?
![image](https://user-images.githubusercontent.com/48493659/107625713-a36fd500-6c54-11eb-8cf4-46dd9d98b716.png)

**Comment by IngoZenz** [comment]
see https://github.com/IngoZenz/personaldnsfilter/issues/137

**Comment by onlytanmoy** [comment]
> see #137

Thanks for the swift response. If I understand correctly this is a known issue and I need to wait for a new version of the pDNSf app to be available in PlayStore, yes?

**Comment by IngoZenz** [comment]
If you like you can also try the dev version attached to #137.
In case you have the version from PlayStore you might need to uninstall first, as the build key is different in the PS version - the configuration would stay.
Alternativly new releases  are published on www.zenz-solutions.de, F-Droid and PlayStore.

**Comment by onlytanmoy** [comment]
@IngoZenz Thanks for your response Ingo. The Current PS version is 1.50.46.0, I will wait for the new update to be available there.
