### ISSUE TITLE
blacklist an app to stop completely its internet access

### ISSUE THREAD

**Issue by lucamp** [IngoZenz/personaldnsfilter#151]
Hi guys,
It would be awesome if there is an option to block internet access entirely to selected apps.
Something like the actual "whitelist" in the setting.

For instance this would be really useful for people that want to use gboard but do not trust google and are afraid it could share what you write.

Cheers
Luca

**Comment by subhasishlak123** [comment]
👍

**Comment by IngoZenz** [comment]
this is not a firewall app but just a dns filter.
In case you want to block dns resolution for all Apps, just add "*" too additionalhosts.txt.
Then you can whitelist those apps, you want to allow...
