### ISSUE TITLE
facebook

### ISSUE THREAD

**Issue by illdeletethis** [IngoZenz/personaldnsfilter#152]
the app keeps letting communications to facebook subdomains through, despite facebook.com being blacklisted in my hosts list.
apart from this i am thankful for its existence.

**Comment by IngoZenz** [comment]
do you see it listed green in the live log? What exactly?
If so, what exactly do you have in the host list?

**Comment by illdeletethis** [comment]
the hosts list contains the lines
facebook.com
facebook.net
but for example connect.facebook.net shows up in green, same happened with some facebook.com subdomains, although i haven"t come across pages that loaded those again

**Comment by IngoZenz** [comment]
in case you have facebook.com in your hosts list, facebook.com and *.facebook.com will be blocked.
Make sure you restart the app after changing host file config.
If issue persists, it would be good to join out TG channel in order to discuss what is wrong on your side.

**Comment by kowith337** [comment]
The domain-wide blocking may only support if you've put rules in the additional hosts in the app, if `facebook.com` alone are loaded from external host/domain rules, possibility of some subdomains won't get blocked if remote rules doesn't have other subs.

Also, please check system apps if some ROMs are installed `Facebook` bloats and/or even any apps that have `Facebook` SDKs if you have any and try to handle them (revoke activities/service/handler {root}, disable, uninstall, etc.) for reduce frequency of connection attempts.

**Comment by illdeletethis** [comment]
Thank you both for your responses
more apps than i was aware contain that garbage, but the blocker works as intended now, i"ll block subdomains should any more get through again, haven"t seen any recently

**Comment by Raj52537** [comment]
To completely block Facebook
Add this in AdditionalHosts file
*facebook*
*fbcdn*
*fbsbx*
This will block all major communication with facebook
Because if you use google.* it will not block www.google.com
But if you put *google* it will block if  google found any where in domain name for example googleapis.com and also android.l.google.com

**Comment by IngoZenz** [comment]
just to clarify: just "facebook" would only block "facebook" and "*.facebook" - it would not block e.g. www.facebook.com. I do not think this is what you want. Maybe you would like to add "*facebook*" which would block all domains having a substring "facebook".
Similar with *google*...
