### ISSUE TITLE
[BUG] DNS Error message

### ISSUE THREAD

**Issue by What-Zit-Tooya** [IngoZenz/personaldnsfilter#154]
Hello there,
I'm using Xiaomi Mi A1 with Android 9 (AndroidOne). I get this message on app:
`java.lang.IndexOutOfBoundsException
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at dnsfilter.DNSServer.readResponseFromStream(DNSServer.java:223)
	at dnsfilter.DoH.resolve(DNSServer.java:462)
	at dnsfilter.DNSCommunicator.requestDNS(DNSCommunicator.java:265)
	at dnsfilter.DNSResolver.processIPPackageMode(DNSResolver.java:171)
	at dnsfilter.DNSResolver.run(DNSResolver.java:221)
	at java.lang.Thread.run(Thread.java:764)
java.lang.IndexOutOfBoundsException
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at dnsfilter.DNSServer.readResponseFromStream(DNSServer.java:223)
	at dnsfilter.DoH.resolve(DNSServer.java:462)
	at dnsfilter.DNSCommunicator.requestDNS(DNSCommunicator.java:265)
	at dnsfilter.DNSResolver.processIPPackageMode(DNSResolver.java:171)
	at dnsfilter.DNSResolver.run(DNSResolver.java:221)
	at java.lang.Thread.run(Thread.java:764)`
![1](https://user-images.githubusercontent.com/9832875/115496042-0c964900-a293-11eb-8e1d-9fd506147d32.png)

I'm using custom DNS, `https://blahdns.com/` with Singapore Server. Any fix?

**Comment by IngoZenz** [comment]
does this always happen?
What in case you use different DNS?

**Comment by What-Zit-Tooya** [comment]
Yes, it always happen , but only when i set DNS settings like this format:
`192.53.175.149::443::DoH::https://doh-sg.blahdns.com/dns-query`

But its does not appear when i set DNS like this:
`192.53.175.149`

Also i added AdGuard DNS along with BlahDNS like this, no error:
`192.53.175.149`
`94.140.14.15`
`94.140.15.16`

**Comment by IngoZenz** [comment]
192.53.175.149::443::DoH::https://doh-sg.blahdns.com/dns-query working fine here - is there a proxy in between? Any other special settings?

**Comment by IngoZenz** [comment]
does it happen for you for for all doh servers or only blahdns?

**Comment by What-Zit-Tooya** [comment]
No proxy and special settings too, I'm in testing with AhaDNS, so far no issue. Will test it throughly. 
Another bug is, personalDNSfilter can't auto start in Android One device, i don't know why. Im using default settings:
- Prevent device sleep : ON
- CNAME cloacking: ON
- Allow only Local DNS proxy Request: ON
- DNS proxy & Root mode: OFF (not rooted fyi)
- Android battery optimization : Not Optimized
I need to manually open the app to start protection, Is there a setting to force it auto start?

**Comment by What-Zit-Tooya** [comment]
Unfortunately, i get error on AhaDNS too, so i can confirm this bug on DOH DNS setting.

![Screenshot_20210423-113858](https://user-images.githubusercontent.com/9832875/115819287-be1ab300-a428-11eb-9f7a-1c1aa1a7139c.png)

**Comment by IngoZenz** [comment]
Regarding the error: Was is it working in teh beginning (you wrote that) and stopped later?
I cannot reproduce it here - so I might need  to provide a debug version giving more information.

Regardiing Autostart: On your Android version I recommend to use always-on VPN in order to start pDNSf after each reboot.
The pDNSf Autostart feature might need further permission - it is device specific - usually it is somewhere near the settings of Battery optimization.

**Comment by What-Zit-Tooya** [comment]
Yep. right, it was working in the beginning, but then stopped. When i press restart, it working again, then stopped with error log appear on log screen. After that most of the logs is spammed with error log.

I'll test your recommendation, need test throuhly on my device works on not.

**Comment by IngoZenz** [comment]
Maybe you want to try attched dev version with additional debug output in case the issue occurs. Would help me to understamd the issue...
[app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/6365033/app-release.zip)

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Maybe you want to try attched dev version with additional debug output in case the issue occurs. Would help me to understamd the issue...
> [app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/6365033/app-release.zip)

Testing now.

For auto start, your recommendation yesterday not work on My device, still needs manual start

**Comment by IngoZenz** [comment]
I know from our TG group that Xiaomi is a bit special with the autostart.
Maybe you want to discuss this issue in our TG group (https://telegram.me/pdnsf). There are a lot of users who could help with this.
Regarding the other issue - waiting for the traces...

**Comment by What-Zit-Tooya** [comment]
Joined, thank you. :)

Here for the traces:

HTTP/1.1 200 OK 
access-control-allow-headers: Content-Type 
access-control-allow-methods: GET, HEAD, OPTIONS, POST 
access-control-allow-origin: * 
access-control-max-age: 3600 
cache-control: private, max-age=198 
content-type: application/dns-message 
date: Sun, 25 Apr 2021 07:58:25 GMT 
expires: Sun, 25 Apr 2021 08:01:43 GMT 
last-modified: Sun, 25 Apr 2021 07:58:25 GMT 
vary: Accept 
transfer-encoding: chunked 
strict-transport-security: max-age=63072000 
referrerpolicy: origin 
x-xss-protection: 1; mode=block; 
x-frame-options: sameorigin 
x-content-type-options: nosniff 

Response size is -1, chunked =true!
IO Error occured! Check network or DNS config!
HTTP/1.1 200 OK 
access-control-allow-headers: Content-Type 
access-control-allow-methods: GET, HEAD, OPTIONS, POST 
access-control-allow-origin: * 
access-control-max-age: 3600 
cache-control: private, max-age=194 
content-type: application/dns-message 
date: Sun, 25 Apr 2021 07:58:29 GMT 
expires: Sun, 25 Apr 2021 08:01:43 GMT 
last-modified: Sun, 25 Apr 2021 07:58:29 GMT 
vary: Accept 
transfer-encoding: chunked 
strict-transport-security: max-age=63072000 
referrerpolicy: origin 
x-xss-protection: 1; mode=block; 
x-frame-options: sameorigin 
x-content-type-options: nosniff

**Comment by IngoZenz** [comment]
ok - thanks...
I will fix this ...

**Comment by What-Zit-Tooya** [comment]
> ok - thanks...
> I will fix this ...

Nice, thank you.
May i know what is the culprit?

**Comment by IngoZenz** [comment]
For some reason the your DOH server (Or some kind of proxy in between) replies with chunked encoding which is not the case usually for DOH. PDNSf expects plain transfer with Content-Length set. I'll change this...

**Comment by What-Zit-Tooya** [comment]
> 
> 
> For some reason your DOH server (Or some kind of proxy in between) replies with chunked encoding which is not the case usually for DOH. PDNSf expects plain transfer with Content-Length set. I'll change this...

Ok, noted.
Btw..for start up on android one can you make "force srtart up" , i can not find how to make pDNSf start in background. Proobably option to turn on persisten notification to prevent system kill pDNSf in the background.
The solutions given on telegram still can not solve my problem.

**Comment by IngoZenz** [comment]
Regarding startup - nothing I can do here - I am doing already everything possible...
If even always-on VPN is not working for you with Battery-optimization disabled, then i seems to be related to your device - it is working for most cases...
Sorry for that ...

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Regarding startup - nothing I can do here - I am doing already everything possible...
> If even always-on VPN is not working for you with Battery-optimization disabled, then i seems to be related to your device - it is working for most cases...
> Sorry for that ...

Ok if you can not do anything, probably my rom fault, using android one is pain in the a$$.

Waiting for new release of DOH fixes...

**Comment by IngoZenz** [comment]
Could you test if DOH is working now?
[app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/6404201/app-release.zip)

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Could you test if DOH is working now?
> [app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/6404567/app-release.zip)

Testing...pls wait

**Comment by What-Zit-Tooya** [comment]
@IngoZenz After testing soome days, i can confirm this work for me

**Comment by IngoZenz** [comment]
Thank you for help!
New version is released.
