### ISSUE TITLE
[Feature Request] Redirect Http request

### ISSUE THREAD

**Issue by mazensmz** [IngoZenz/personaldnsfilter#155]
Hi, 
I am not sure if it's already available.

I want to redirect specific sites to local servers or any other servers.

E.g if https://www.abc.com is requested, http://local host:1234 will be open 

Regards...

**Comment by IngoZenz** [comment]
This is a DNS based filter, no an httpproxy.
You can map host names to own IPs within additionalHosts.txt ...

```
# In order to forward to custom ip add a ">" in front
# of the host name followed by whitespace and mapped IP

>router.home 192.168.2.1
```
