### ISSUE TITLE
[Query]Enabling DNS over HTTPS?

### ISSUE THREAD

**Issue by onlytanmoy** [IngoZenz/personaldnsfilter#158]
Hi mate @IngoZenz trust you are doing well.
Please let me know how to enable DNS over HTTPS via pDNSf.

When I went to the below site to test
https://www.cloudflare.com/en-gb/ssl/encrypted-sni/

and clicked 'check my browser', there were no green ticks against Secure DNS and DNSSEC.

**Comment by IngoZenz** [comment]
Could you discuss this in our TG group?
https://telegram.me/pdnsf

**Comment by onlytanmoy** [comment]
Sure, are you online there now? Think it will be good to do in your presence 🙂

**Comment by IngoZenz** [comment]
There are many people with good knowledge - I am usually following the discussions but unfortunately do not have time to answer all questions ... however I help as much as I can ...
Btw: did you click already the "?" Button to get some guidance? 
Did you configure DNS servers and disable DNS discovery?

**Comment by IngoZenz** [comment]
For Cloudflare you need to add following DNS config

#for DOT
1.1.1.1::853::dot

#for DOH
1.1.1.1::443::doh::https://cloudflare-dns.com/dns-query

**Comment by onlytanmoy** [comment]
Thanks mate for sharing those DNS config details.
Please can you point me to some guide on how to add the DNS configs 😊

**Comment by IngoZenz** [comment]
1. touch dns field.
2. remove everything
3. just add the following:
```
1.1.1.1::853::dot
1.1.1.1::443::doh::https://cloudflare-dns.com/dns-query
```
Further questions, please join the TG ;-)

**Comment by onlytanmoy** [comment]
Cool, thanks mate 😊 have a nice rest of the day.
