### ISSUE TITLE
ReadRead error: ssl=....

### ISSUE THREAD

**Issue by unknown4849** [IngoZenz/personaldnsfilter#160]
i got this error...
```
Read error: ssl=0x6f72425408: I/O error during system call, Connection reset by peer
IO Error occured! Check network or DNS config!
```
i use blahdns and cloudflare , but this error while using blahdns.

so what this mean error ? I do not completely understand ,

**Comment by IngoZenz** [comment]
does this happen every time? Or randomly? In case it is random, it is sporadic network issues, otherwise might be related to some SSL issues between your phone and blahdns.   Is it an old phone?

**Comment by unknown4849** [comment]
randomly , but before this error often occurs (when using nextdns) *this old problem*, no still new phone .

while this problem appears , my pc still connected

**Comment by unknown4849** [comment]
well... F.... , i know now why notice SSL=... cause my phone for some reason with or without personaldns ( i disable it at same time) got problem like connected but not get internet access.... , so... this problem not related app 

Sorry....

**Comment by unknown4849** [comment]
well... F.... , i know now why notice SSL=... cause my phone for some reason with or without personaldns ( i disable it at same time) got problem like connected but not get internet access.... , so... this problem not related app 

Sorry....
