### ISSUE TITLE
Blahdns does not work in personaldnsfilter

### ISSUE THREAD

**Issue by jw243** [IngoZenz/personaldnsfilter#163]
personaldnsfilter can't reach any Blahdns server, neither via dot nor doh. This is my configuration:

159.69.198.101::853::DOT::dot-de.blahdns.com
95.216.212.177::853::DOT::dot-fi.blahdns.com
45.91.92.121::853::DOT::dot-ch.blahdns.com
159.69.198.101::443::DOH::https://doh-de.blahdns.com/dns-query
95.216.212.177::443::DOH::https://doh-fi.blahdns.com/dns-query
45.91.92.121::443::DOH::https://doh-ch.blahdns.com/dns-query
176.9.93.198::853::DOT::dnsforge.de
176.9.1.117::853::DOT::dnsforge.de
176.9.93.198::443::DOH::https://dnsforge.de/dns-query
176.9.1.117::443::DOH::https://dnsforge.de/dns-query
159.69.114.157::853::DOT::fdns2.dismail.de
80.241.218.68::853::DOT::fdns1.dismail.de

**Comment by d-adi4** [comment]
> personaldnsfilter can't reach any Blahdns server, neither via dot nor doh. This is my configuration:
> 
> 159.69.198.101::853::DOT::dot-de.blahdns.com
> 95.216.212.177::853::DOT::dot-fi.blahdns.com
> 45.91.92.121::853::DOT::dot-ch.blahdns.com
> 159.69.198.101::443::DOH::https://doh-de.blahdns.com/dns-query
> 95.216.212.177::443::DOH::https://doh-fi.blahdns.com/dns-query
> 45.91.92.121::443::DOH::https://doh-ch.blahdns.com/dns-query
> 176.9.93.198::853::DOT::dnsforge.de
> 176.9.1.117::853::DOT::dnsforge.de
> 176.9.93.198::443::DOH::https://dnsforge.de/dns-query
> 176.9.1.117::443::DOH::https://dnsforge.de/dns-query
> 159.69.114.157::853::DOT::fdns2.dismail.de
> 80.241.218.68::853::DOT::fdns1.dismail.de

am having the same issue

**Comment by jw243** [comment]
Today, it seems to work again. Probably was some kind of problem with the blahdns servers yesterday.

Be aware though, that the IP of the german blahdns server has changed to 78.46.244.143.

**Comment by IngoZenz** [comment]
Thanks for updating! I was also trying - currently blahndns   seems pretty unstable to me...
