### ISSUE TITLE
personaldnsfilter together with AFWall

### ISSUE THREAD

**Issue by jw243** [IngoZenz/personaldnsfilter#164]
I am trying to use personaldnsfilter in root mode (without local VPN) together with AFWall, but the result is that all internet access is blocked.

Do I need any special settings in AFWall to get this to work or is it not possible at all?

Thanks for your help!

Edit: This problem does not happen on all devices. On my MotoX4 (Lineage 17.1), personaldnsfilter and AFWall work together without a problem, on my Galaxy Tab S2 8.0 (Lineage 16.0), the combination results in blocked internet access.

**Comment by IngoZenz** [comment]
I suggest to discuss such very special issues in the Telegram group...
Depending what you set in AFWall, it might conflict with iptable rules in root mode ...
Guess you also might run pDNSf in proxy mode only (without root mode) and do the iptable magic in AFWall...

**Comment by IngoZenz** [comment]
I close this as this is nothing we can discuss here ...

**Comment by CircleCode** [comment]
Since afwall is complementary with pDNSf for people caring about privacy, I think this question is worth an faq…
Do you have any advice on afwall and pDNSf cohabitation after the discussion on telegram?

**Comment by CircleCode** [comment]
@IngoZenz did you find any solution to enable root mode (without local VPN) together with AFWall?
(For some reasons, I cannot use telegram, and thus cannot discuss it on the group…)
