### ISSUE TITLE
Bug: DNS configuration window keeps popping up

### ISSUE THREAD

**Issue by jw243** [IngoZenz/personaldnsfilter#165]
**Steps to reproduce:**
1. Open the DNS configuration window.
2. _Optional: make some changes in the DNS configuration_
3. Close the DNS configuration window again.
4. Switch to another app (bring personaldnsfilter into background) or close the app in the app overview.
5. Bring personaldnsfilter into foreground again.
6. DNS configuration window pops up again, sometimes even together with the on-screen-keyboard.

**What should happen instead:**
When personaldnsfilter is brought back into the foreground, the DNS configuration window should not pop up again.

**How this can be overcome:**
The only way to prevent the popping up is to stop the app ("Beenden") and start the app fresh. As soon as you open the DNS configuration window again, the bug returns.

It would be great if you could get rid of this bug.

Thanks a lot!

**Comment by ryder203** [comment]
If the DNS config window is opened, just press the back button on the navigation bar or do the back gesture if you use gesture input on Android. Then the window closes itself. A close or back button for that window is planned for future releases.
