### ISSUE TITLE
Build steps for jar file

### ISSUE THREAD

**Issue by gkrishnaks** [IngoZenz/personaldnsfilter#166]
Hi,  clarification needed:
In your website, both .apk and .jar are available for download. Can you please share build steps to build a jar (that can run on a Pi) from this sourcecode repo? 
Thanks.

**Comment by IngoZenz** [comment]
For building the jar,  you have to exclude the dnsfilter.android package and you have to package the assets directly within the root of the jar file. Nothing special in addition...

**Comment by gkrishnaks** [comment]
Thanks, I will try it out.

**Comment by gkrishnaks** [comment]
Able to build the jar as per the steps you mentioned. Thank you.
