### ISSUE TITLE
How to edit dnsfilter.conf?

### ISSUE THREAD

**Issue by TimotheAlbouy** [IngoZenz/personaldnsfilter#172]
Sorry for the (outrageously) ridiculous question, but I haven't found anywhere how to open the `dnsfilter.conf` file on the smartphone.

The smartphone I'm working on is a Huawei, and some of you may know that, since 2017, it is not possible to root these smartphones anymore because the company stopped giving bootloader codes. So I need a non-root solution.

What I tried is: create a `PersonalDNSfilter` folder in `/storage/emulated/0/` (or in other words, the local storage), and in it, I copy/pasted the [`dnsfilter.conf`](https://github.com/IngoZenz/personaldnsfilter/blob/master/app/src/main/assets/dnsfilter.conf) file with the modifications I wanted to make. However, it does not seem to work.

My "root" problem (excuse the pun) is that pDNSf does not work on Android Chrome for me. I followed every step of [this page](https://www.zenz-solutions.de/faq/) (section *"Why does personalDNSfilter not block ads on Android using Google Chrome browser?"*):
- I disabled private DNS in Android network settings;
- I disabled Data Saver in Chrome settings;
- I was not concerned by the asynchronous DNS step;
- I disabled secure DNS in Chrome settings;
- I rebooted the phone.

So the only option remaining is to edit `dnsfilter.conf` and set `routeUnderlyingDNS = true`, but as I told you, what I did has not worked. Please help.

**Comment by ryder203** [comment]
Strange thing. The last time I checked all was good with chrome and pDNSf using the mentioned settings. But I use bromite rather than chrome.

The config is in storage/Android/data/dnsfilter.android/files/PersonalDNSFilter/

Be sure to backup stuff.

**Comment by TimotheAlbouy** [comment]
> The config is in storage/Android/data/dnsfilter.android/files/PersonalDNSFilter/

Thank you! I edited the `/storage/Android/data/dnsfilter.android/files/PersonalDNSFilter/dnsfilter.conf` file, I rebooted the smartphone and it finally works!
