### ISSUE TITLE
Whitelisting Wildcards in v1.50.50.0

### ISSUE THREAD

**Issue by slcw** [IngoZenz/personaldnsfilter#176]
I'm thrilled about having the ability to use wildcards (*) in the whitelist, but I think the implementation may be problematic.

Consider the following whitelist entry w/wildcard:
`!*.bit.ly`
If I go to `bit.ly` or `www.bit.ly`, the whitelisting is ignored and the host will be blocked.

However, if I use this entry instead:
`!*bit.ly`
The whitelisting works and I'm able to connect to `bit.ly` and `www.bit.ly`.

What makes this problematic is that it will whitelist any hostname that happens to end in `*bit.ly`, like `robit.ly`. I think the wildcard should be before the dot notation:
`!*.bit.ly`
That way, it's matching on `bit.ly` and any subdomains (like `mail.bit.ly`), not any additional domains that are incidentally matched.

**Comment by IngoZenz** [comment]
Actually
!*.bit.ly should not whitelist bit.ly but whitelist www.bit.ly.
If this is not the case s.th. is wrong.

**Comment by IngoZenz** [comment]
Just checked with:

!*.test.de
*

Everything is blocked except any subdomain of test.de.
test.de is blocked
www.test.de is allowed
So for me works as designed...
Please check again...

**Comment by slcw** [comment]
Yes, that's exactly what I originally said. I don't know what you intended for the wildcard whitelisting, but I think `!*.bit.ly` should whitelist `bit.ly` in addition to any subdomains. Unless the plan is to seperately whitelist the domain and subdomains rather than do it with a single line.

**Comment by IngoZenz** [comment]
`!*.bit.ly `does not match the string `bit.ly `- so actually works as designed ...
in case you want to white list `bit.ly` in addition just add `!bit.ly`

**Comment by slcw** [comment]
Very good. I apologize if I wasted your time with my misunderstanding. I think I was using my experience with NextDNS as a basis for my view of how the whitelisting should work. Their whitelisting works the way I describe, with the wildcard host applying to the base domain. In any case, all hail pDNSf!

**Comment by IngoZenz** [comment]
Thank you :-)
I also need to correct my self:
In my sample above:

```
!test.de
*
```
www.test,de would still be blocked because "*" would hit first.  So in case in this examplke you also want to whiltelist all subdomains of test.de, you should add as follows:

_!test.de
!*.test.de
*_

Note that teh sequence of the wildcard entries have effect here!
