### ISSUE TITLE
Revert to TCP broken if routeIPs is used

### ISSUE THREAD

**Issue by quaqo** [IngoZenz/personaldnsfilter#178]
Referring to #173, the workaround to use routeIPs in lieu of routerUnderlying in addition to render all services on that IP unavailable (but that's expected), breaks the new "revert to TCP" feature: pDNSf tries to actually contact itself (I didn't take a look at the code so I don't know why UPD works, but I imagine is set up before routIPs comes into place?).

**Comment by IngoZenz** [comment]
workarround should be to whitelist "dnsfilter.android".
I plan to  fix this with next release...

**Comment by IngoZenz** [comment]
will be part of next release
