### ISSUE TITLE
Allow configuration files to be imported and reloaded from local filesystem.

### ISSUE THREAD

**Issue by DUOLabs333** [IngoZenz/personaldnsfilter#182]
All configuration has to be done in the app. It would be nice if you allow configuration to be done outside the app, then imported into it, and reloaded on restart.

**Comment by slcw** [comment]
You can edit the `dnsfilter.conf` file in any text editor, and it will be merged in on the next restart.

**Comment by DUOLabs333** [comment]
Where us `dnsfilter.conf` kept?

**Comment by slcw** [comment]
`<storage root>/Android/data/dnsfilter.android/files/PersonalDNSFilter/dnsfilter.conf`

**Comment by IngoZenz** [comment]
you can also just copy and paste from the config file and additional hosts UIs
