### ISSUE TITLE
[Feature request]: Firewall (block network acess on selected apps)

### ISSUE THREAD

**Issue by mooms06** [IngoZenz/personaldnsfilter#184]
Hi, 

Thank you for this app, I've switched for it (came from TrackerControl), but I miss one major function: firewall.

Would you consider adding this feature ?

Regards.

**Comment by Zulgrib** [comment]
iptables require root

**Comment by mooms06** [comment]
I never mentioned iptables.
TrackerControl is able to do it, so it's possible to restrict network access without root.

**Comment by IngoZenz** [comment]
firewall is not in scope for pDNSf - it is a DNS filter only.

**Comment by IngoZenz** [comment]
> And what about #209

updated
