### ISSUE TITLE
[Feature Request] Add quick tile toggle

### ISSUE THREAD

**Issue by MF-Debug** [IngoZenz/personaldnsfilter#19]
a quick tile toggle to turn the vpn on/off would be great for devices running android 7+.

**Comment by IngoZenz** [comment]
what's special there for android 7+?

**Comment by killoid** [comment]
iirc, adding quick tile toggle of an app is not possible in android <7.

**Comment by Laicure** [comment]
If that doesn't work on Android <7 then... what about a simple Notification Toggle like from DNS66?

**Comment by Yellowbeans01** [comment]
Please this! I downloaded an app just so I could put pDNSf in the Quick Settings/Pull Down and get to it easier

**Comment by IngoZenz** [comment]
You can now pause / activate Blocking via an action within the notification
