### ISSUE TITLE
[Enhancement]Scripts for Linux(System-wide Installaion Script and Systemd Service File)

### ISSUE THREAD

**Issue by lovenemesis** [IngoZenz/personaldnsfilter#190]
Hi,

As I don't see the scripts that distributed in released full package zip file in the code repo, I create this issue with the titled scripts in attachment.

Currently the full package only provides the a simple start.sh script for running personalDNSfilter on Linux system. This is far from enough for anyone who wish to run this as the primary DNS on her/his local machine or even network wise.

Following the manner of "Windows-Scripts", I have written below scripts and README targeting Linux OS.

[Linux-Scripts.zip](https://github.com/IngoZenz/personaldnsfilter/files/7858721/Linux-Scripts.zip)

Those scripts were tested on Fedora 35 X64, Debian Buster ARM32 and Debian Bullseye ARM64. Theoretically it should work on any Linux distro with bash and systemd.

I'm hoping these scripts could be bundled in full package of personalDNSfilter future release so that desktop Linux users can benefit from this awesome app, just like Windows ones.

Thanks,

**Comment by IngoZenz** [comment]
This really cool and I was waiting for this - Thank you! :-)
I will review this and also add it to the full package. 
I'll also add the scripts to the repo.

**Comment by lovenemesis** [comment]
Update the install.sh script to fix an existence check for the dnsfilter.conf.

**Comment by IngoZenz** [comment]
Added to dev branch with https://github.com/IngoZenz/personaldnsfilter/commit/c5454c98a5e106f5820f87ebbf97a885d4871d0a.
Will be packaged with the next release.
Feel free to file pull requests for further changes.
Thanks again :-)

**Comment by lovenemesis** [comment]
Raised PR https://github.com/IngoZenz/personaldnsfilter/pull/191

**Comment by lovenemesis** [comment]
Should be good for now as PR #192 was merged.
