### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by b0** [IngoZenz/personaldnsfilter#193]
Currently, pDNSf is not available in Play Store search on TVs with Android TV.

Is this addition possible?

br

**Comment by IngoZenz** [comment]
Wasn't aware - we'll look into this

**Comment by ryder203** [comment]
I added it some weeks ago. Is it available for you @b0 ?

**Comment by IngoZenz** [comment]
Yes - Google did not accept pDNSf app for Android TV - bigger changes in the app would be required. There is no plan for this currently. You can directly install the app from the web side or f-droid. It won't be shown on the launcher screen but it would be listed in the app list.
