### ISSUE TITLE
Firewall - pdnsf - dnscrypt

### ISSUE THREAD

**Issue by Horizonbli** [IngoZenz/personaldnsfilter#195]
Hello,

Currently my mobile setup is: firewall (VPN mode) forwarding connections to pdnsf, which on its turn forwards to dnscrypt-proxy.

pDNSf seems not to acknowledge when dnscrypt-proxy blocks something, and shows connections as being allowed (green). The logs show they are blocked, though.
Is there a way for pdnsf to either show dnscrypt-proxy blocked queries as beeing blocked (red) or a different colour (orange, for example), even if revealing them as allowed?

Thanks

**Comment by IngoZenz** [comment]
No plan currently - but we'll put it on the list.
What does dnscrypt return in case of filtered dns?

**Comment by Horizonbli** [comment]
dnscrypt-proxy shows A Reject, if pattern blocklist is used, or A Cloak, if cloaking is used.

pDNSf log shows A - 13 domain, # This query has been locally blocked by dnscrypt-proxy...

I wonder if the reason why pDNSf GUI shows as passing, because on android 8+ (I think), blocked queries must be set with HInfo on dnscrypt-proxy... I tried with "refused", but didn't seem to have no effect.

Thanks

**Comment by IngoZenz** [comment]
pDNSf checks the requested domain against the filter and does the corresponding red / green live log. This is independent on the response.  I have no plans to change this currently - so you ,might need to check the traffic log to find out ...
