### ISSUE TITLE
The log setting is reset when I restart

### ISSUE THREAD

**Issue by nehad243** [IngoZenz/personaldnsfilter#197]
Hello. I'm using the latest Android apk(1.50.51.0).
I always pause the log to reduce my battery usage.
But when I restart the app, the log is always resumed.
I know the battery usage is slightly. But I want to stop the logging.
Can I stop logging permanently?

**Comment by IngoZenz** [comment]
No  - sorry but  live log can not be switched off - it also doesn't use any battery.
