### ISSUE TITLE
[Question] Is there an easier way to clear the log files?

### ISSUE THREAD

**Issue by my-password-is-password** [IngoZenz/personaldnsfilter#2]
Right now to clear the log files I delete the files but after you delete them any new connections made aren't logged until I ```Restart``` PersonalDNSFilter.   Can there a be a ```Clear log files``` button or is there an app you recommend I use to view and clear them?

One more thing, is it possible to log which app made the request?  It would help to know which app to uninstall.

Thank for your awesome app.

PersonalDNSFilter 1.50.13
Android 4.3

**Comment by IngoZenz** [comment]
I do not understand the usecase for clearing the log files? They are rotating so they won't grow forever. 
Logging the "app" - yes that really makes sense. So far I did not find a way on how to detect the requesting app. Seems this is not possible via the android VPNService. If anybody knows, I would be happy to learn!

**Comment by my-password-is-password** [comment]
I just hated scrolling all the way to the bottom of the log file when it got too big.  I guess I could set the log file size to be smaller than the default 1 MB in dnsfilter.conf.  I'll try that out.  Thanks

**Comment by IngoZenz** [comment]
yes you can configure the size
