### ISSUE TITLE
RouteUnderlyingDNS not working w/DNS proxy mode

### ISSUE THREAD

**Issue by slcw** [IngoZenz/personaldnsfilter#204]
When using pDNSf in DNS proxy mode, it doesn't look like the RouteUnderlyingDNS functionality is working. Is this intentional, or a known bug?

**Comment by IngoZenz** [comment]
In root mode all DNS on port 53 is routed over pDNSf.
In proxy mode without root, this is technically not possible.
So in short: works as designed...

**Comment by slcw** [comment]
I suspected as much. Thank you for taking the time to respond.
