### ISSUE TITLE
problem dns.nixnet

### ISSUE THREAD

**Issue by Gamefire238** [IngoZenz/personaldnsfilter#205]
Looks like dns.nixnet has closed based on the following link [https://docs.nixnet.services/NixNet_DNS](https://docs.nixnet.services/NixNet_DNS)
Log fiter
***Initializing personalDNSfilter Version 1505100!***
Using directory: /storage/emulated/0/Android/data/dnsfilter.android/files/PersonalDNSFilter/
Acquired WIFI lock and partial wake lock!
Released WIFI lock and partial wake lock!
Using blocking mode!
VPN connected!
VPN runner thread 2 started!
Selected DNS: (-1ms) [104.244.78.231]::853::DOT
Connection refused
IO Error occured! Check network or DNS config!
16:59:58
DNS filter: Next filter reload:Tue Mar 15 12:41:18 GMT+08:00 2022
17:00:03
Selected DNS: (-1ms) [104.244.78.231]::853::DOT
17:00:08
Selected DNS: (-1ms) [104.244.78.231]::853::DOT
17:00:10
Selected DNS: (-1ms) [104.244.78.231]::853::DOT
17:00:13
Selected DNS: (-1ms) [104.244.78.231]::853::DOT
17:00:15
Selected DNS: (-1ms) [104.244.78.231]::853::DOT
17:00:20
Selected DNS: (-1ms) [104.244.78.231]::853::DOT
17:00:24
Selected DNS: (-1ms) [104.244.78.231]::853::DOT
DNS filter stopped!

**Comment by IngoZenz** [comment]
ok - thanks for letting me know. Will remove this with next release

**Comment by IngoZenz** [comment]
fixed with https://github.com/IngoZenz/personaldnsfilter/commit/6096eb7c2f21bf1d60351b5caee52db9b12801e9
