### ISSUE TITLE
"Add Filter" button not available on Android 12 MIUI 13

### ISSUE THREAD

**Issue by adamzea** [IngoZenz/personaldnsfilter#208]
The "Add Filter" button no longer shows when tap&holding on a domain name in the log. Only system options appear on Android 12 MIUI 13. Instead, I have to copy/paste entries into the "Configure additional hosts" list.

![Screenshot_2022-04-13-18-36-15-010_dnsfilter android](https://user-images.githubusercontent.com/24486391/163281564-ceb3f482-35e5-4594-a43b-fe42c4f44371.jpg)

**Comment by IngoZenz** [comment]
it is a known issue with Xiaomi devices  - the are doing so much proprietary changes to android....
Will see what I can do ...

**Comment by IngoZenz** [comment]
Maybe you can try the attached version and let me know if it helps, and also if there are special messages in the message (footer) bar.

[app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/8530777/app-release.zip)

**Comment by adamzea** [comment]
> [app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/8530777/app-release.zip)


That update almost worked... the add/remove filter buttons appeared at the top of the log frame independent of the context menu, but that only happened once and I can't get those buttons to reappear. 

![Screenshot_2022-04-21-17-12-12-841_dnsfilter android](https://user-images.githubusercontent.com/24486391/164553593-cc0654e1-f8b1-42e9-9e0b-209269ac8349.jpg)
![Screenshot_2022-04-21-17-13-56-689_dnsfilter android](https://user-images.githubusercontent.com/24486391/164553598-2cc0179c-bf79-4a9d-883b-fb9f6b379e52.jpg)

**Comment by IngoZenz** [comment]
Thanks for letting me know.
As already discussed, MIUI devices have an issue with custom action menus as it is used for the add/remove filter action menu.
I have added a fallback option.
You can enable it by setting  the following dnsfilter.conf setting:

```
# useActionMenuFallback - set this to true in case your device does not support custom action menus (e.g. Xiomi)
useActionMenuFallback = **true**
```

It is implemented in attached dev version and will be integrated in next official release . Let me know if this works for you.

[app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/8538472/app-release.zip)

**Comment by adamzea** [comment]
That fixed it (temporarily)! Now the add/remove filter buttons appear at the top of the log frame after selecting a host in the log. Awesome! Thanks for the fix!
There is a little selection zoom window appearing over the host names in the log when selected, but that's not a big deal. 

![Screenshot_2022-04-22-08-50-52-607_dnsfilter android](https://user-images.githubusercontent.com/24486391/164718108-7aa7594a-0922-4a4f-b58f-941e6eaf80d2.jpg)

However, if I tap and hold a hostname while the log scrolls this selecting multiple lines, or I accidentally tap some other part of the log, then Xiaomi's selection menu appears and breaks the add/remove filter buttons for the rest of the app session. Closing and restarting the app brings the add/remove filter button functionality back. 

![Screenshot_2022-04-22-09-01-42-277_dnsfilter android](https://user-images.githubusercontent.com/24486391/164719475-5e4c4be8-2b0e-4fce-947a-556ae4bdc985.jpg)

Sorry Xiaomi's customizations mess things up in the tap&hold menu. :(

**Comment by IngoZenz** [comment]
very wired this Xiaomi mess....
Maybe you can try again the latest dev-03 and see if it is better....
[app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/8541698/app-release.zip)

**Comment by IngoZenz** [comment]
in case dev-03 does not work, try dev-04 below.
Sorry for bothering, but I do not have such device to test...
[app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/8541760/app-release.zip)
.

**Comment by adamzea** [comment]
Dev-03 seems to work. Looks like you removed the ability to select anything else in the log window thus removing any chance for Xiaomi's menu to appear. I'm ok with that, but I don't know if other people liked the ability to select the entire log to copy somewhere else. 
![Screenshot_2022-04-22-10-49-33-172_dnsfilter android](https://user-images.githubusercontent.com/24486391/164738990-86c520ef-847a-4145-a28e-67864e51bf6e.jpg)

Dev-04 brings back the ability to select multiple lines in the log, but without any way to copy those lines (so it looks like you're still trying to keep the copy log capability, correct?) The add/remove filter buttons still work well in this build. 

![Screenshot_2022-04-22-10-54-13-746_dnsfilter android](https://user-images.githubusercontent.com/24486391/164740084-79bc43c4-c2d9-4c44-88cf-1fb0ecd8f9ae.jpg)

**Comment by IngoZenz** [comment]
dev-03 should allow to copy additional lines .... in case the selection starts with a filter or block line, the buttons on top of the log should come up, but noting from Xiaomi Action menu. 
In case s.th is selected which is not starting with  a filter or block line, the normal Xiaomi logic should kick in ...
But according to the info you have provided, this is not working as expected on Xiaomi - right?!
So I am not sure how to proceed ...

**Comment by IngoZenz** [comment]
This is a small video showing how dev-03 works on normal phoned ;-)
https://user-images.githubusercontent.com/11963504/164746565-d83a80da-9888-4e4e-9e67-da7b1564899e.mp4

**Comment by IngoZenz** [comment]
I think with next version I'll do it in a way, that the Buttons are displayed in addition to the action menu, as in attached version.
Would this work for you? Then I would close the issue.
[app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/8620247/app-release.zip)

**Comment by IngoZenz** [comment]
`useActionMenuFallback = true` should solve the issue in release 150.53.5
