### ISSUE TITLE
support for proxy

### ISSUE THREAD

**Issue by d-adi4** [IngoZenz/personaldnsfilter#21]
Thanks for this app.. just on side note, may you add proxy support as well like in personalhttpproxy.. [proxy]:[port] .. cause personalhttpproxy has been deprecated.. please consider if this is possible..

**Comment by d-adi4** [comment]
Thanks for this app.. just on side note, may you add proxy support as well like in personalhttpproxy.. [proxy]:[port] .. cause personalhttpproxy has been deprecated.. please consider if this is possible..

**Comment by IngoZenz** [comment]
I won't mix both apps into one. I am also wondering why 1 would still need the proxy when having the dns filter. Most of the http traffic is meanwhile anyhow in https so that only hosts based filtering works and no URL filtering.
Maybe I will bring the proxy to the new UI at some point in time ...

**Comment by d-adi4** [comment]
It not mixing both apps.. it just picking one feature to merge with pdnsf, and for need of proxy.. let's say one is using Firefox browser and having built in proxy but even if pdnsf is on but Firefox will load all advertisement cause all passing through proxy but not pdnsf itself.. it will be better to add it cause adding it will not increase size of app.. and at last.. implement only if it is feasible and possible and according to pdnsf policy otherwise pdnsf alone doing good work.. :)

**Comment by IngoZenz** [comment]
sorry - no plans ;-)
