### ISSUE TITLE
AdList Suggestion

### ISSUE THREAD

**Issue by CipherOps** [IngoZenz/personaldnsfilter#210]
I maintain a list that is compiled of known malware/spam/tracking links, as well as custom URL's I've found to be ad serving URL's that are missed by most default adlists, including the ones already in the app.

https://raw.githubusercontent.com/CipherOps/AdList/main/Blocklist

**Comment by IngoZenz** [comment]
URLs do not work in pDNSf - it is a dns based host filter.
