### ISSUE TITLE
add OISD in the default sources list

### ISSUE THREAD

**Issue by lucamp** [IngoZenz/personaldnsfilter#211]
Hi,
please add [OISD](https://oisd.nl/) in the default list of available sources.

As stated in the [download page](https://oisd.nl/downloads) they have 3 lists specific for personalDNSfilter:

- Full | https://dbl.oisd.nl/
- basic | https://dbl.oisd.nl/basic/
- nsfw | https://dbl.oisd.nl/nsfw/

nsfw is indipendent from the others

Thanks for yor app
Luca

**Comment by lucamp** [comment]
OISD Basic have been added with 1.50.53.5 but mistyped as OSID instead of OISD

**Comment by ryder203** [comment]
Done.
