### ISSUE TITLE
Added Allowlist doesn't seem to work

### ISSUE THREAD

**Issue by Elaborendum** [IngoZenz/personaldnsfilter#217]
I'm trying to add an [allowlist](https://github.com/EnergizedProtection/unblock) to counteract a blocklist that can sometimes be too aggressive with sites I regularly use (So both lists are regularly conflicting). However, even if pDNSf doesn't show any errors with it, it doesn't seem to allow anything.

Manually whitelisting a domain works as intended.

**Comment by IngoZenz** [comment]
How do you set this allowlist in pDNSf?

**Comment by slcw** [comment]
You need to copy/paste the contents of that allowlist into the "additional hosts" file. pDNSf doesn't have the ability to facilitate allow lists the same way it handles blocklists.

-- 

Respectfully,

Samuel Walter
***@***.***

Jul 10, 2022 9:07:24 AM Elaborendum ***@***.***>:

**Comment by IngoZenz** [comment]
This only allows block lists...

If you want to whitelist s.th., you need to use additionalHosts...
