### ISSUE TITLE
[Feature request] Ability to see which app is requesting which site

### ISSUE THREAD

**Issue by AlphaElwedritsch** [IngoZenz/personaldnsfilter#221]
Is it possible to implement a functionaöity to see what app has triggered an event (forwarded-green, or blocked-red)
Maybe via longpress on event and it's contextmenue. like the same as used to add or remove filter

it would be nice and helpfull to get the info which app tried to access this blocked or allowed host

or is it already possible but i still didn't find it yet

![photo1657877466](https://user-images.githubusercontent.com/109347938/179200974-d35127fc-9ef2-4c1b-9388-081fad7d14ce.jpeg)

**Comment by IngoZenz** [comment]
unfortunately it is technically not possible to get the app doing a DNS request as on Linux those requests come from the system it self.
