### ISSUE TITLE
Problems of pdnsf running on honor system

### ISSUE THREAD

**Issue by biange200** [IngoZenz/personaldnsfilter#226]
Pdnsf cannot filter advertisements on the honor mobile phone. Besides, the installation and operation will stop automatically after a while, and the log will not be recorded

![Screenshot_20220727_212931.jpg](https://user-images.githubusercontent.com/37582806/181735975-866f97d2-115f-4202-a71f-284c6e145c86.jpg)
![Screenshot_20220727_212627.jpg](https://user-images.githubusercontent.com/37582806/181736020-affeac81-1c9c-4116-a071-aa6e210c3875.jpg)
![Screenshot_20220729_174956.jpg](https://user-images.githubusercontent.com/37582806/181736375-4fb08f41-ee7a-438d-864b-73b07cd54de7.jpg)
![Screenshot_20220728_100632.jpg](https://user-images.githubusercontent.com/37582806/181736454-b0795e60-b036-4a16-818e-fb35c51f5a2f.jpg)

**Comment by ryder203** [comment]
Please read the help and the FAQ
https://www.zenz-solutions.de/faq/
https://www.zenz-solutions.de/help/
Join our Telegram group and check the other website...
https://t.me/pDNSf
https://dontkillmyapp.com/huawei
