### ISSUE TITLE
Not able to change `Configure Additional Hosts` settings

### ISSUE THREAD

**Issue by BlackDex** [IngoZenz/personaldnsfilter#227]
Hello there,

For some strange reason I'm not able to edit the `Configure additional hosts` anymore in a useful way.
The window doesn't sizes correctly or something.
See the screenshot below.

pdns version: v1505202
Android version: 11 (Patch level - July 1, 2022)
Android kernel: 4.4.205-perf+

I tried to clear the cache, force-stop, both didn't worked.
I have not tried to do an uninstall/clear data yet.

The `Edit Config File` option btw does work.
As do all other settings windows.

If you need more information, please let me know.

Screenshot:
![Screenshot_20220801-105126](https://user-images.githubusercontent.com/610450/182131398-2a6dac56-6af8-4876-8a02-8863df96d78a.png)

**Comment by IngoZenz** [comment]
seems you deleted the default config and comments from additionalHosts.txt.

You can retrieve it by restoring default configuration via adv. settings -> backup & restoreMessage ID: ***@***.***>

**Comment by BlackDex** [comment]
Hmm, i didn't changed anything my self in a long time on that file.
So that is a bit strange though.

**Comment by BlackDex** [comment]
Well, i tried to do a restore, and that seems to have solved the issue.
Maybe it is because of some rights which changed during an update.

I can't access the files anymore via a file manager now, which i could before.
Also, creating a backup now is rather useless, since it stores it within `Android/data` which I'm not able to access anymore with a file-manager.

**Comment by BlackDex** [comment]
Since it seems to work now, ill close this
