### ISSUE TITLE
Scrolling not possible

### ISSUE THREAD

**Issue by eliashaeussler** [IngoZenz/personaldnsfilter#24]
Hi,

on my Honor 9, running Android 8.0, I'm not able to scroll the view of the app in case I have activated the "extended settings" checkmark (Screenshot attached). This causes me not to be able to see the logs at the bottom of the view. It seems that the view is not scrollable. Can you fix this?

Thanks for your great work!

![Screenshot_20190317-110757](https://user-images.githubusercontent.com/16313625/54488667-f4c68c80-48a4-11e9-91c1-4289e41179ea.jpg)

**Comment by IngoZenz** [comment]
Currently you have to uncheck advanced settings to see the other UIs again.
I might  consider your feedback for future releases
