### ISSUE TITLE
[Question] I just wanted to change my dns to cloudfare dns but its too complicated for me can someone please help me?

### ISSUE THREAD

**Issue by killerrook** [IngoZenz/personaldnsfilter#245]
It claims to change have ability to change dns on Google play but i'm still having a hard time configuring it could someone please help me?

**Comment by ChaosNicro** [comment]
Click the pencil next to the dns-field, activate the checkbox, delete the existing entries, add "1.1.1.1" as a line, confirm, hit restart. 
That said, for just this the official app "1.1.1.1" on the store can do that more easily. Telemetry not withstanding.
