### ISSUE TITLE
[Feature Request] Toggles and etc

### ISSUE THREAD

**Issue by Laicure** [IngoZenz/personaldnsfilter#25]
Hi!

Thanks for the app! It is working very well on my Xperia xz2, Pie :D

There is a few points I want to see in app:
- Toggle to turn-off the persistent notification (I don't just want to hide it using Android natively)
- Toggle not to auto-start the VPN when opening the app (I want to update first, configure first, whitelist, and etc before starting the VPN service)
- Toggle to whitelist all system apps (There are times that I only want Chrome (or other browsers) to be filtered in the VPN)
- Option to remove all _overrule_ in the conf file (I only want the app to respect only and just only the domains I imported from urls; I manually remove all overrule)
- Option to remove all pre-installed category/sources (I manually remove all, I use my own [list](https://github.com/Laicure/HostsY_hosts))
- Toggle to turn-off/on the traffic logger file instead of manually editing the conf
- Auto-restart the VPN service (not only the thread) to properly release the connection whenever changing the DNS, updating the filters, whitelisting an app, and configuring other domains/hosts (had a connectivity problem just now because of that; cannot connect when dns is changed while VPN service is on)

I think that's all for now 🤭

Thanks and I hope you implement those. 🤗

**Comment by Laicure** [comment]
Also, can you add the app name in the logs?
![_20190411_125305](https://user-images.githubusercontent.com/8619566/55931697-23901280-5c59-11e9-8808-0720235c62e0.JPG)


like..
com.chrome.com: doubleclick.net

**Comment by IngoZenz** [comment]
Android does not allow to get the app name - sorry...
Most of your requests above are very special - usefull for very few users only- Sorry but I have to set priorities due to very limited time ;-)
The point with teh overrule is valid. The last point I do not understand (cannot connect when dns is changed while VPN service is on)

**Comment by Laicure** [comment]
ohh ok no worries ;)

/hmm
for the last point, so it is like...
- connected to DNS A (automatic): access to blocked site is not possible
- enable Manual DNS; DNS B: access to blocked site still not possible
- close-open app: access to blocked site now possible

I can close this one now :D
