### ISSUE TITLE
Hairpinning not working

### ISSUE THREAD

**Issue by optimusprimespace** [IngoZenz/personaldnsfilter#253]
Having a website open to the internet, and running a pi-hole dns server, i set the DNS-Server-Configuration to manual and set the local dns server ip address, but the local dns record that was set up by pi-hole doesn't work, because when i ping the website's domain name i get the public ip address not the local one. On other machines this works and on other android phones too without personaldnsfilter. I'm running the latest release of the app. Is this a feature or a bug?

**Comment by IngoZenz** [comment]
could you please share your personalDNSfilter dnsfilter.conf file? Or a screenshot of your dns configuration

**Comment by optimusprimespace** [comment]
Here are the photos of my config:
![2eedf1da-fd8f-4207-a363-96c5a9eff7cb](https://user-images.githubusercontent.com/62800678/204337536-c53282d2-3e35-4aaa-8188-01d7fc7fbe0e.jpg)
![b4f4fa02-a2aa-4b15-88c2-5aa31212ff7c](https://user-images.githubusercontent.com/62800678/204337543-18e45e5f-79a3-4acc-87df-31e8ecce5673.jpg)

**Comment by optimusprimespace** [comment]
Sorry, something was up with my router, i did the ping and now it returns the local address. :)
