### ISSUE TITLE
Google Maps offline maps update stuck at 0%

### ISSUE THREAD

**Issue by Shallrath** [IngoZenz/personaldnsfilter#257]
Hi,

When personaldnsfilter is active and Google Maps tries to update my offline maps, the download remains stuck at 0%. There is always an active notification that says "Downloading offline maps 0%". This happens both for automatic updates as well as downloading new offline maps or triggering an update manually.
When personaldnsfilter is active and I attempt a maps update, I don't see anything blocked in personaldnsfilter's log but the progress remains at 0%. As soon as I disable personaldnsfilter, the download progresses as expected.

I am also using personaldnsfilter to use an alternative DNS server but I disabled this feature to check and the maps download still didn't work.

I am using a Samsung Galaxy S7 with Android 8.0.0

**Comment by IngoZenz** [comment]
Maybe just whitlelist the Google Map app...
