### ISSUE TITLE
[Feature Request] Systemizing/Priv-apping PDNSF on rootless systems

### ISSUE THREAD

**Issue by ChaosNicro** [IngoZenz/personaldnsfilter#259]
Heya,
I would like to try and systemize the app since I dislike root/magisk but have access to /system on my GSI. I'm not sure if the file access will work out but the existing root-mode could work given that the right permissions are granted.
Has this use-case been considered before?
What Android-permissions are expected by the app to function in non-vpn-/root-mode?

Thank you for providing this project.
PS: If there are issue-templates enabled, Github isn't offering them to me. So I'm manually categorizing them in the title.

**Comment by IngoZenz** [comment]
The root mode requires the permission to add iptable rules ... I do not think you can request this as Android permission.
In addition file access to the app folder is needed ...
The manifest request these permissions:
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>
```
Regards, Ingo

**Comment by ChaosNicro** [comment]
Thanks for the info, I was hoping to replicate what IoDE-OS did with their rootless firewall. It turns out that they severely gutted SELinux and patched the network stack to make it work. Not a solution to strive for.
I also tried to point the network settings to the local proxy, but the "secure dns"-feature only takes a hostname without a port and the wifi settings only take a manual dns address when DHCP is completely disabled.
Hard to believe that Google will not provide an interface for this.
If there are no further ideas on this it can be closed.

**Comment by IngoZenz** [comment]
Thanks! in this case let's close this
