### ISSUE TITLE
[Feature Request] Possibility to use wildcards in Active Filters

### ISSUE THREAD

**Issue by DansLeRuSH** [IngoZenz/personaldnsfilter#262]
Hi,

Small demand that could be useful to set up quickly large scale of blocking : would it be possible to use wildcards on hosted lists and use them in active filters ?

For example, instead of having a complete (and to be updated frequently) list like [Facebook-extended](https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt), a wildcards list like [BlockMeta](https://dansleco.de/danslerush/dns-filters/raw/branch/main/BlockMeta.txt).

Yes, for that, we can use "additionnal blocking list" but it could be more convenient to manage them on a repo (or elsewhere).

Would this be possible ?

Thank you in advance and in any case ! 🖖

Best regards,
Franck

**Comment by IngoZenz** [comment]
Hi,
it has low prio to me as you can copy and paste such entries into additionalHosts.txt today and as you correctly stated such list is pretty stable.
Regards, Ingo

**Comment by DansLeRuSH** [comment]
Hello and very well,

I can understand ... just, as I said, it would be more practical to be able to use remote settings and especially backups, less costly in monitoring time. Above all, do what you can !

Best regards,
Franck

**Comment by ckuethe** [comment]
I'd like to see this too, so I can share rules between devices such as my phone and tablet. I've got my list of domain blocks, and I'd like to share my wildcard filters too.

**Comment by IngoZenz** [comment]
wildcard lists are pretty expensive from Memory Consumption and performance point of view. Especially when people start to import huge widlcard lists. Therefore I want to restrict this to additionalhosts config file.
As pdnf blocks already all sub domains of a specific host entries from the filter lists, the need for wildcards shouldn't be rather low.

**Comment by IngoZenz** [comment]
I might add support for host filters with these special wildcard entries like `*.<host>` as we see them in https://small.oisd.nl/domainswild. I would simply convert such entry to `<host>`.

**Comment by IngoZenz** [comment]
I have added support for *.<host> entries to the dev version in order to support filters like https://small.oisd.nl/domainswild. Other wildcard entries won't be supported in filter files.
[pdnsf-dev.zip](https://github.com/IngoZenz/personaldnsfilter/files/13849463/pdnsf-dev.zip)

**Comment by DansLeRuSH** [comment]
In any case, it's going to make things a lot easier, thank you for that ! 🖖

**Comment by DansLeRuSH** [comment]
PS : It works great, thank you very much !
