### ISSUE TITLE
pDNSf (even in proxy mode) seems to keep RethinkDNS from auto-starting its 'VPN' at boot

### ISSUE THREAD

**Issue by Rhys-T** [IngoZenz/personaldnsfilter#264]
I've been trying to combine pDNSf (in DNS proxy mode) with [Rethink DNS + Firewall][rethink], so that I can do both custom host addresses and per-app blocking. It generally works well, but for some reason, Rethink can't auto-connect to its pseudo-VPN when the device starts up. It shows the "Protected!" notification for just a moment, then changes to "Warning: RethinkDNS has been deactivated". I can start Rethink manually without issue, however.

pDNSf by itself, in VPN mode with Rethink turned off, can start itself just fine - so it doesn't seem to be an OEM modification messing up auto-starting VPNs. And if I turn on Rethink, disable the pDNSf app entirely (through `adb`), and reboot, Rethink successfully auto-connects - and stays connected when I re-enable pDNSf.

**Edit**: Okay, `adb` was overkill - just turning off the autostart setting in pDNSf was enough to let Rethink's autostart work.

Looking at `BootUpReceiver`, pDNSf seems to call `VpnService.prepare(...)` regardless of whether it's in VPN or proxy mode, as long as the SDK version is new enough. Is this intentional? Could that be kicking Rethink out of the VPN slot at boot time? (Note: I have basically no experience with Android development, especially VPN apps, so it's entirely possible I'm misunderstanding what this code is doing.) https://github.com/IngoZenz/personaldnsfilter/blob/78e2d3dee53e82408a309b7c2e57d27a9b5970c0/app/src/main/java/dnsfilter/android/BootUpReceiver.java#L44-L56

[rethink]: https://github.com/celzero/rethink-app

**Comment by IngoZenz** [comment]
You could be right. For sure pDNSf should not call VpnService.prepare(context) in non VPN mode. It might cause your issue. Thanks for you detailed analysis.

**Comment by IngoZenz** [comment]
please check if https://github.com/IngoZenz/personaldnsfilter/commit/4137c049a59b6efa2ff459ce18d7f1945d726b9e fixes the issue. Binary attached!
[app-release.zip](https://github.com/IngoZenz/personaldnsfilter/files/11359055/app-release.zip)

**Comment by Rhys-T** [comment]
Had to figure out how to get the data ported over from the F-Droid version (see #149), but now that I have that straightened out, it seems to work perfectly. Whether I set {Rethink: on, pDNSf: proxy mode} or {Rethink: off, pDNSf: VPN mode}, it seems to come up in the same state after I reboot. Thanks!

**Comment by Rhys-T** [comment]
I had switched over to that test build, and didn't realize until today that that change had made it into a normal release. I've migrated my settings back to the F-Droid build, v1.50.55.2, and it still seems to work correctly and not interfere with Rethink.

Thanks again for looking into this!
