### ISSUE TITLE
Show the specific hosts entry which blocked a server

### ISSUE THREAD

**Issue by elyoas** [IngoZenz/personaldnsfilter#265]
In the live log inside the app, show the specific hosts entry which blocked a server. For example currently it shows:

```X   dit.whatsapp.net```

It would be very useful if it also showed:

``` 0.0.0.0 whatsapp.net```

There are hosts lists of millions of lines. Sometimes an important server gets blocked because of multiple of unrelated addresses being blocked. It would be nice if it was possible to see them so that it becomes easier to remove them.

**Comment by IngoZenz** [comment]
red X entries are always 0.0.0.0 / :: entries

**Comment by elyoas** [comment]
Thanks.
