### ISSUE TITLE
Redirecting a domain does not work

### ISSUE THREAD

**Issue by elyoas** [IngoZenz/personaldnsfilter#267]
On my LineageOS, I update the /etc/hosts file to include the line:
`216.239.38.120 www.google.com`

Which forces google safe search across the whole phone.

But if I put this line in my *personaldnsfilter* hosts, it does not work and it blocks google entirely.

Is not this a bug? Adding this line to the /etc/hosts file is one of the main reasons why I use LineageOS. Thanks.

**Comment by IngoZenz** [comment]
custom IPs can only be configured in additional hosts configuration (see adv. settings).
Add the entry `>www.google.com 216.239.38.120` to additional hosts will do the job

**Comment by elyoas** [comment]
Thank you!
