### ISSUE TITLE
Is it possible to add CIDR bits to "Additional hosts"?

### ISSUE THREAD

**Issue by elyoas** [IngoZenz/personaldnsfilter#269]
I'm sorry but I could not find this information anywhere.

Say I want to block all addresses ranging from ip `1.128.42.0` to `1.128.42.128`, can I add this entry to the Additional hosts file to block all addresses:
`>1.128.42.0/25 0.0.0.0`

Or would I need to add an entry to every single address?

**Comment by IngoZenz** [comment]
it won't work at all this is a DNS based host filter and not a firewall. Only blocking and forwarding of host names is supported.

**Comment by elyoas** [comment]
@IngoZenz I think this is the only feature missing to let personaldnsfilter function as a firewall. Do you consider investing your time in this direction?

**Comment by IngoZenz** [comment]
sorry but "No", Firewall is not in scope for personalDNSfilter.
