### ISSUE TITLE
Routing USB-Tether Traffic via Mobile VPN(DNS-Filter)

### ISSUE THREAD

**Issue by SparKot** [IngoZenz/personaldnsfilter#27]
Does DNS lookups from a PC pass through MobileVPN(DNS-Filter) when Mobile(Android) is tethered via USB to a PC/Laptop?
I don't see it in logs nor in blocking action which are listed on Android device.

Since DoT & DoH are now active in this DNS-Filter, it would greatly improve PC/Laptop browsing experience which are tethered to Internet via Android phone.

I'm currently using Stubby on Ubuntu to avail DoT.

cheers

**Comment by IngoZenz** [comment]
Seems Tetering is NOT using the VPN connection on Android!

**Comment by IngoZenz** [comment]
There is nothing I can do for this - sorry!
