### ISSUE TITLE
Domains being blocked without being explicitly named

### ISSUE THREAD

**Issue by elyoas** [IngoZenz/personaldnsfilter#270]
I have a short list of domains (390kb) (adult content) to be blocked:
[list_here](https://raw.githubusercontent.com/elyoas/DNS-Filter-Android-Testing/main/ba.c)

This list puzzlingly blocks
_youtube.com
github.com
linkedin.com
ewtn.com_

I can't understand what is going on, none of these domains are defined at all in the list..

**Comment by IngoZenz** [comment]
Maybe there are other lists marked active? Or anything in additionalhosts?
Also note that after a change in the filter config a restart of the app is required.

**Comment by elyoas** [comment]
It's perplexing because I have tried and verified all these steps. I have even uninstalled the app, installed it again and I used the single list above as the only one:
https://raw.githubusercontent.com/elyoas/DNS-Filter-Android-Testing/main/ba.c

The websites still get blocked..

**Comment by elyoas** [comment]
Actually not. I just wrote a script to check the domains. It contains the following line:
0.0.0.0 com
which understandably blocks all these domains. Thanks very much!
