### ISSUE TITLE
(Discussion) Request to extend 'additional syntax support' for adblocker

### ISSUE THREAD

**Issue by Universalizer** [IngoZenz/personaldnsfilter#277]
Hello @IngoZenz, Gratitude for this wonderful light weight app.

I do know, this app is primarily personal DNS filter,
But Request to extend 'additional syntax support' for adblocker at VPN or Firewall Level.

If possible.

**Comment by IngoZenz** [comment]
It is a DNS Filter, no firewall app....so your feature request is out of scope for personaldnsfilter...
