### ISSUE TITLE
[Feature Request] Blocking apps from internet

### ISSUE THREAD

**Issue by baraa272** [IngoZenz/personaldnsfilter#28]
Hi dev 
Thanks very much for all the work you did now 
I actually moved from Blockada to personal dnsfilter 
Blockada was giving me some resource hogging problems and didn't have doh/dot 
Anyway thanks to your simple lightweight app I have 2million rule with doh(dns over https) without affecting the device performance (s7 edge)
But there's something still missing I think 
The choice to block apps from internet completely 
I would love to see this feature in your amazing app 
Again thanks for hard work

**Comment by IngoZenz** [comment]
With version 1.50.32 (released soon) there will be the option to add wildcard based hosts within additional Hosts config. If you  add just "*", everything will be blocked. You could whitelist the apps you want to allow.

**Comment by IngoZenz** [comment]
I am closing this as 1.50.32 is out
