### ISSUE TITLE
[help] cannot install OpenVPNforPDNSF.apk - app not installed as package seems to be invalid

### ISSUE THREAD

**Issue by redcat42** [IngoZenz/personaldnsfilter#283]
keep getting the error on Android 14, lineageos with mindthegapps

https://github.com/IngoZenz/ics-openvpn/releases/download/0.0.3/OpenVPNforPDNSF.apk

app not installed as package seems to be invalid

thanks

![Screenshot_20240112-054928_Trebuchet](https://github.com/IngoZenz/personaldnsfilter/assets/113236440/7c1b3097-aafd-4b2f-89a6-e4ee9b77783b)

**Comment by IngoZenz** [comment]
Please try with https://www.zenz-solutions.de/?sdm_process_download=1&download_id=272

**Comment by redcat42** [comment]
that worked, thank you
