### ISSUE TITLE
query regarding whitelists

### ISSUE THREAD

**Issue by redcat42** [IngoZenz/personaldnsfilter#285]
would sites added to the whitelist go via the VPN (not using the app in local VPN mode, using with openvpn), I couldn't test, thought I'll ask

also, 
sites added manually to the whitelist get cached somewhere in the app, adding sites manually works, removing sites them from the whitelist manually and reloading filter and restarting does not help, storage of the app has to be purged or installing from scratch is required to remove a URL from whitelist, once added manually, 

it's not a big deal for me, just thought I would let you know

I guess if I select the URL in log and once it is highlighted I click on 'remove filter' it would work, in that case, manual editing of whitelist/blacklist should not be allowed ... only via highliting to add/remove via log

thanks for your work 🙏

**Comment by IngoZenz** [comment]
also whitelisted sites will go via the VPN, only filterring won't be applied.
Regarding caching - the app cache is cleared after restart of the app. In case you use openVPN for DNS you might also need to restart the VPN in order to clear the DNS cache on your device.

**Comment by redcat42** [comment]
thank you
