### ISSUE TITLE
[help] is it possible to use personaldnsfilter as a private dns

### ISSUE THREAD

**Issue by redcat42** [IngoZenz/personaldnsfilter#287]
hi
is it possible to use personalDNSfilter as a private DNS
for example adding
ten.ten.ten.ten 
below, I tried it didn't work
thanks 
edit: I'm not rooted
I guess it wouldn't work
was hoping it would work in the same way pihole works
![Screenshot_20240202-182838_Trebuchet_1](https://github.com/IngoZenz/personaldnsfilter/assets/113236440/a4878730-aade-40c1-bdf9-fc236ec6ed33)

**Comment by IngoZenz** [comment]
No, this is not possible.
