### ISSUE TITLE
[help] understanding 'prevent device sleep' option

### ISSUE THREAD

**Issue by redcat42** [IngoZenz/personaldnsfilter#289]
i use macrodroid app to turn off WiFi when my screen is off and turn on WiFi when device unlocked 

i would like to know in my use case, mentioned above, if i use personalDNSfilter, do i need to turn on 'prevent device sleep'

when i unlock the device, and WiFi gets turned on automatically, for personalDNSfilter would it be better to keep 'prevent device sleep' on or off

thanks

**Comment by IngoZenz** [comment]
Keep it off ...

**Comment by redcat42** [comment]
understood. thank you
