### ISSUE TITLE
Dnscrypt Proxy Documentation

### ISSUE THREAD

**Issue by Revenrof** [IngoZenz/personaldnsfilter#29]
Is there any dnscrypt proxy documentation lying around? Cause I can't get it to work - still detect my ISP DNS.

Thanks.

**Comment by baraa272** [comment]
Use adgaurd DOH 
Works on my end

**Comment by baraa272** [comment]
Can give screenshot of config if want

**Comment by IngoZenz** [comment]
if you tab the dns field within personalDNSfilter you will come into a settings box where you can configure the DNS servers. Disable the dns detection (check the checkbox)  and here you can configure to use the dnscrypt proxy.

**Comment by d-adi4** [comment]
Here is how user can configure dnscrypt-proxy to work with personalDNSfilter:-

Step 1:
Open dnsfilter.conf from /sdcard/PersonalDNSfilter folder and search following line and write true;

# manageDNSCryptProxy - Only for Android version
# if true, an installed DNScryptProxy will be started and stopped together with DNSFilter (requires root!)
manageDNSCryptProxy = true

step 2:
Now open PersonalDNSfilter app and tap on its DNS field and delete all custom DNS address write there and write Only following address;
127.0.0.1::53::UDP
Now close DNS field pop-up and restart app.

That's it, now you have working dnscrypt-proxy with PersonalDNSfilter app.

Step 3:
Now, you can customise dnscrypt-proxy by its dnscrypt-proxy.toml file located under /system/etc/dnscrypt-proxy folder. Enable those features what one wanna use and disable what doesn't.

Pre-requisite:
1. User has to install dnscrypt-proxy for Android zip on its own. Personaldnsfilter doesn't come along with dnscrypt-proxy binary, it only utilise and work alongside but only if user has it installed.

2. Using magisk module by bluemeda is preferable, user can find it in magisk download repo section.

3. While installing bluemeda dnscrypt-proxy zip, make sure to choose option no. 2 (set DNS with 3rd party app) by volume down button.
