### ISSUE TITLE
Consider expanding the allowable regular expressions

### ISSUE THREAD

**Issue by elyahw** [IngoZenz/personaldnsfilter#294]
Currently it's only possible to use the `*` to cover all domains of the form `*.google.com` (`google.com` alone would have the same effect).

Consider adding an expanded regular expression, for example the rule:

`[0-9]{3,3}[a-z]{2,2}\.com`

To cover: `123aa.com`, `111zz.com` etc.

**Comment by IngoZenz** [comment]
you can use `*` also within the String and not only as *.hostname (e.g. `*ads*.com`).
Currently there are no plans to add support for regular expressions.

**Comment by IngoZenz** [comment]
I am closing the issue with the comment above
