### ISSUE TITLE
Privacy Policy Page Update

### ISSUE THREAD

**Issue by RicoHeat** [IngoZenz/personaldnsfilter#295]
https://www.zenz-solutions.de/personaldnsfilter-privacy/

Needs an update.. It still has links to the ghost of Energized.

![Screenshot_20240315_062506](https://github.com/IngoZenz/personaldnsfilter/assets/41478458/c22d5ca7-38b7-4c3a-8c9b-f82f32856167)

Have a great day 👍

**Comment by IngoZenz** [comment]
Thanks for letting me know. I'll fix this comming days...

**Comment by IngoZenz** [comment]
Fixed! Thanks again!
