### ISSUE TITLE
Fragmented Packet

### ISSUE THREAD

**Issue by saleho27** [IngoZenz/personaldnsfilter#296]
I don't think this is an issue, I just want to know is there any plan to implement feature of chunking packets? Just like other dns filter app with bypass dpi features.

Apologize for my bad english 😅

**Comment by IngoZenz** [comment]
bypass dpi is not posssible with personalDNSfilter as it only works on the DNS packets and NOT overall data traffic.

**Comment by saleho27** [comment]
Yup I know, but what I mean, only fragmented the tls handshake, but I dunno is it possible or not with udp

I am trying to fragment the tls sni packet using personalHttpProxy with codes from gfw knocker and it works!!!

Yeah, only the header, only the tls handshaker, split it to 65-117 pieces with some delay

So I dont think about fragmenting the whole packet

Thanks a lot for your response Ize, may be you can get some inspirations, I only add 2 classes from other github source to combine it with personalHttpProxy and it works very well, all isp can be bypassed, who knows it can works too with pdnsf

**Comment by IngoZenz** [comment]
pDNSf only sees the dns traffic wheras personalHTTPproxy interferres overall http / https traffic.
Maybe you want to share your work on personalHttpProxy?

**Comment by saleho27** [comment]
Honestly I am a noob Ize, but I will pm you via telegram and explain what I have done, I hope you can get the inspirations. Many thanks!!!
