### ISSUE TITLE
Slightly suspicious behaviour

### ISSUE THREAD

**Issue by mcbegamerxx954** [IngoZenz/personaldnsfilter#297]
In  [virustotal](https://www.virustotal.com/gui/file/f7ba460edfada6f4085b3d51eded864ac9341ecdd6e0d522b53f4344940f5304/behavior) it shows the fdroid app connecting to this random GitHub page from a user that joined 1 month ago with some base64 in its [html](https://github.com/rbeie207fdh/rbeie2071.github.io/blob/main/index.html).
Would really like an explanation to this.

**Comment by IngoZenz** [comment]
personalDNSfilter is not connecting anything except the configured DNS servers and filterlist servers.

**Comment by mcbegamerxx954** [comment]
> personalDNSfilter is not connecting anything except the configured DNS servers and filterlist servers.
> 

From what virustotal is showing in the sandbox, it makes this http request on pretty much startup, but since its not seeming to be doing much else than that im not sure

**Comment by IngoZenz** [comment]
You say the personalDNSfilter android app is doing this? Actually this can't be the case. The app is 100% self-contained without additional libraries. I also do not believe that F-Droid build adds s.th. in addition.  So I think  it must be s.th. else.

**Comment by mcbegamerxx954** [comment]
I do believe that fdroid would not do such a thing and that your app has no deps, but i want to clear this doubt and find the source of it

**Comment by IngoZenz** [comment]
I am closing this as there is nothing in pDNSf app doing this. Let me know in case there is new information on this topic.
