### ISSUE TITLE
"Prevent device sleep" does not function

### ISSUE THREAD

**Issue by PeterBadzhakov** [IngoZenz/personaldnsfilter#31]
**Device:**
Nokia 3.1 - Android 9.
Stock ROM, developer mode on. No OS behaviour-altering apps.
personalDNSfilter downloaded and regularly updated from F-Droid.
**Problem:**
Occasionally personalDNSfilter gets shut down on locked screen. App still open in "recent items" screen. Switching to or opening personalDNSfilter automatically turns it on again.
**Remedies tried:**
Turning off all battery saving features for all apps.
Whitelisting app via adb.

**App still gets shut down automatically.**

**Comment by IngoZenz** [comment]
Are you on latest version 1.50.32? Did you configure Always on VPN for pDNSf?

**Comment by PeterBadzhakov** [comment]
Yes, 1.50.32.
Turned Always-on VPN on and device indefinitely lasts on standby, unplugged, without turning off pDNSf.
Thank you!

**Comment by PeterBadzhakov** [comment]
App still turned off despite always-on VPN status. Tried all combination of always-on VPN, adb whitelist, and dumpsys deviceidle disable - none help.
There is no connection with internet connectivity - device did not move from my desk all day, on a strong and stable wifi contact.

**Comment by IngoZenz** [comment]
Did you try previous versions? Is it the same there?

**Comment by PeterBadzhakov** [comment]
Deleted all app data, installed V1.50.29 from F-Droid. Restarted phone, dumpsys deviceidle disable. Always-on VPN option grayed out, unclickable.
Phone left overnight with pDNSf running, strong and stable wi-fi connection. Found app disabled in the morning.

**Comment by IngoZenz** [comment]
Ok...so it least it isn't related to the latest version, which in fact should have improved the situation via always on vpn support and startup as forground service. I suggest to install the latest version again, enable always on vpn and investigate there.  Do you have access to any device logs? You might filter for dnsfilter.
Do you have similar issues with other apps on your device?

**Comment by PeterBadzhakov** [comment]
Thank you for your help. Yes, I had the same shutoff problem with practically all VPN services with no resolution. 
I have found several Mediatek services related to power management and neutralised them. Several hours in without problems. Hopefully, that was it and not this nice app. Still testing.

**Comment by PeterBadzhakov** [comment]
That solved it, it was a Mediatek power savings feature. Thanks again for the help.
