### ISSUE TITLE
Barmer App crashes when personalDNSfilter is active

### ISSUE THREAD

**Issue by desisn** [IngoZenz/personaldnsfilter#316]
The main Barmer app (8.6 million clients in Germany) is crashing when the App is active on my Samsung S23. There is lots of other people complaining about the app crashing, that might be running a similar adblocker like AdAway or something, but I tried the App with Blokada and it worked, so it must be something about personalDNSfilter that disturbs the Barmer app. I have whitelisted the Barmer app within personalDNSfilter, but it still did not work and will immediately crash the app. If I close personalDNSfilter it immediately works again to start the app.

Link to Barmer app: https://play.google.com/store/apps/details?id=de.barmergek.serviceapp&hl=de

**Comment by IngoZenz** [comment]
Are you sure you whitelisted the Barmer app and restarted personalDNSfilter afterwards?

**Comment by desisn** [comment]
Yes, 100% it is whitelisted and I restarted. You can easily check by downloading the app and seeing the behaviour yourself. The app will crash immediately if personalDNSfilter is enabled...

**Comment by IngoZenz** [comment]
I was able to reproduce it but no idea why this is happening. Maybe it is a bug in Barmer app in combination with vpn. I think best would be to contact Barmer app support.

**Comment by desisn** [comment]
Yes, I already told them about the crashing, seems unlikely they fix the bug. They have tons of login problems for over a year and did not fix them. I have not had many more bug ridden apps on Android so far.

Thanks for checking though.
