### ISSUE TITLE
prefer local DNS server

### ISSUE THREAD

**Issue by PurryPlatypus** [IngoZenz/personaldnsfilter#32]
My local (LAN) DNS server resolves several internal addresses, e.g. my Nextcloud, for file sync, calendar and contacts. However, DAVx5 (cal/card sync) often issues failure notifications, because my phone (or this app?) suddenly decides to use Google's DNS servers. My local DHCP server is configured to tell clients the proper local DNS IP.

I'm on a Galaxy S7, Android 8, latest updates. pDNSfilter from F-droid repo, latest.

Edit: fixed typo

**Comment by IngoZenz** [comment]
Can you post the DNS config within pDNSf?
In the DNS Config the option to use manually configured DNS servers should be disabled. In this case it should use the network DNS - unless something failes with detecting the network DNS.

**Comment by PurryPlatypus** [comment]
Hi, I didn't know that pDNSf has a manual DNS feature. It's visually not obvious that the DNS field has a touch event that opens another configuration dialogue. It speaks a design language that I'm not familiar with. It's greyed out, which usually indicates inactive elements. Maybe a little cog wheel or a wrench symbol next to it makes it more obvious.

Yes, it was disabled. But now I've enabled it and added my local DNS server before everything else.

If you like, I could restore the default and conduct a few test scenarios. Like dropping in and out of WiFi range, with 4G enabled / disabled.

**Comment by IngoZenz** [comment]
Feedback taken with regards to the DNS config - Thanks!
Regarding the issue: Would be good to know if there is any error in the log when it switches to the fallback DNS. 
Can you reproduce this? If so, what are the steps / actions?

**Comment by PurryPlatypus** [comment]
It happened again while the phone sat on its wireless charging pad, connected to my local a/ac WiFi. The screen was off and unattended while I enjoyed a hot bath for over 1 hour, consuming YouTube on my Windows tablet, via the same WiFi.

Here are the logs. 

(normal operation)
No DNS Response from /REDACTED_LOCAL_DNS_IP:53
IO Error occured! Check network or DNS Config!
(normal operation)
No DNS Response from /8.8.8.8:53
IO Error occured! Check network or DNS Config!
(normal operation with 3rd fall-back 8.8.4.4)

This time, the manually defined list of DNS servers was active, 3 entries, my local one first.

Timeouts to tight?

I'll investigate further; it might just be a crooked power management setting, that turns off the WiFi radio during long periods of inactivity. Or there's a local network congestion issue. Maybe even on layer 1. I'll set up a few ping probes.

Also, log entries with timestamps would be useful.

After several hours of continuously pinging my phone's IP, from multiple topological locations, I've made the following observations:
* echo responses take 100 up to over 2500 ms, that's over 2 whole seconds - when the phone is in use (unlocked)
* echo replies generally tend to arrive in bursts of 2 or 3
* while locked / lock screen / screen off, echoes arrive in bursts of ~6, every 6 seconds
* after a while the phone becomes "Destination Host Unreachable", but responds every once in a while

By now, I'm pretty sure that I'm struggling with power management settings, although I haven't actually reproduced the issue yet.

I'll keep on testing. I'll let you know when I'm absolutely sure of the cause.

**Comment by IngoZenz** [comment]
PDNSf switches the DNS server to the next in the list whenever an Error with the current Server occurs.
This might happen e.g. when the network goes to sleep. Best for your case would just be to configure your DNS as only one in the list. We still would need to investigate, why the auto detection does not work in your case

**Comment by PurryPlatypus** [comment]
During my ping test, I also pinged my local DNS server IP with absolutely flawless results: * WiFi, >11000 packets, avg response <2ms, max 115ms, 0% loss (Windows 10 tablet with Ubuntu Linux subsystem [WSL])
* wired gigabit, >10000 packets,  max 5.2ms, 0% loss

I've noticed an unexpected restart in my (OPNsense/  Unbound DNS) server logs. However, I can not, with certainty, verify this to be the cause.

If you intend to include timestamps in pDNSf error logs, please use the ISO, or rfc3339, formatting (sortable, with seconds and UTC offset). I think it's fine to leave the red/green block/pass logs as they are.

**Comment by PurryPlatypus** [comment]
I'm now, 2 week later, very confident that my issue was the result of me excluding the DAVx5 App from my phone's power saving mode (locked & display off). I didn't observe further errors / warnings since i removed the exception for DAVx5 in my power management settings.

**Comment by IngoZenz** [comment]
Thanks for the update!
...so is the dns auto detection working now as well ?

**Comment by IngoZenz** [comment]
seems to be resolved
