### ISSUE TITLE
Make APK files available through GitHub

### ISSUE THREAD

**Issue by slcw** [IngoZenz/personaldnsfilter#321]
It would be amazing if you pushed APKs through your GitHub repo rather than force people to download it from the pDNSf website, or wait for the f-droid release. I'd like to be able to expand the Assets section of a particular release, and see the associated APK in addition to the source zip and tar files. It would make obtaining the latest release via Obtainium a lot quicker, and with less manual action.

**Comment by slcw** [comment]
Izzy is cool, but it's a bit esoteric. If releases are made available through Github, they can be downloaded directly from the repo as soon as they're pushed, or through a frontend like Obtainium. I think it would ultimately be more accessible than if it was pushed through Izzy. My goal is to be alerted the minute a new release is pushed, and have a way of downloading it while the code is still hot. It always takes time to get the release into fdroid repos, and that's what I'm looking to avoid.

**Comment by IngoZenz** [comment]
The app is already available today on f-droid.

**Comment by slcw** [comment]
I'm aware, but that's not really the same as making it available as a release through your GitHub repo. There's a delay between when a new release is announced, and when it's available on f-droid. Downloading from the website after the release notice is currently the quickest way to get the latest release. I use Obtainium to pull application releases as soon as they're available, and have a janky workaround that pulls from the pDNSf website, but it would be preferable for the release to come directly through GitHub, but for reliable, speedy updates, and to satisfy my OCD. Obviously, not the world, but is there some specific reason why apk releases aren't pushed through GitHub? Or is it just a byproduct of your workflow?

**Comment by IngoZenz** [comment]
the problem is that github seems to have removed the option to upload additional assets to a release via the web page and I did not figure out yet how to do it via gh script.
