### ISSUE TITLE
personalDNSfilter can't parse pure IPv6 DoH

### ISSUE THREAD

**Issue by tomac4t** [IngoZenz/personaldnsfilter#327]
I add OpenDNS DoH `https://[2620:119:fc::2]/dns-query` to manual DNS servers. Then I test the connection, but failed: `Failed: Bad request - Cannot Paese port int: POST https://[2620:119:fc: HTTP/1.1` I think pDNSf doesn't handle IPv6 addresses correctly, the part after the colon is truncated.

Screenshot: 
![personaldnsfilrer-ipv6](https://github.com/user-attachments/assets/5a8a2245-41bf-40b5-9b70-53db7abd305a)

I can also see the truncated IPv6 address in Edit configuration file:
`fallbackDNS = [2620:119:fc::2]::443::DOH::https://[2620:119:fc`

**Comment by IngoZenz** [comment]
Thanks for raising this. It is fixed in dev with https://github.com/IngoZenz/personaldnsfilter/commit/588f4c4d1a3fecf0add21612c811c89fa3e729a6!
Build attached!


[app-release.zip](https://github.com/user-attachments/files/17607083/app-release.zip)

**Comment by IngoZenz** [comment]
Just noticed it is not fixing fully currently - it still saves the corrupted URL. Will check further ....

**Comment by IngoZenz** [comment]
should be finally fixed with https://github.com/IngoZenz/personaldnsfilter/commit/c4e5bc429cc889954f74788c8ea3a5008fac3249!
[app-release.zip](https://github.com/user-attachments/files/17607302/app-release.zip)
