### ISSUE TITLE
Android Notification about "High battery consumption" after Update 

### ISSUE THREAD

**Issue by tioannidis** [IngoZenz/personaldnsfilter#33]
Hello,

since the update to version 1.50.32.1 I receive the following system notification the hole time:
![2019-04-27](https://user-images.githubusercontent.com/1592909/56848046-49b5e380-68e4-11e9-9991-cf71c6267200.png)

A downgrade to version 1.50.30.1 helps to avoid this notification.
Why does this message appear only in the latest version?

I have the Moto G5, with Android 8.1.0 unrooted. 
Do you need any informations?

Regards,
Theo

**Comment by IngoZenz** [comment]
but is it really consuming Battery? Usually it shouldn't take much.
In order to avoid that the service gets killed by android (happens on some devices), I need to start the service in a special forgound mode. I guess this is the reason for the notification. But normally it should only display the message "DNSFilter is running".
So would be really interresting to know if there is a real Battery consumption issue in your case ...

**Comment by tioannidis** [comment]
I'm not sure about the battery consumption. At the moment it displays 21 mAh for the last 2 hours. But I'm not sure if Android displays the battery consumption correctly.

But I've noticed that only if I disable  your Message about the runing dns Service in the status bar the Android diplays the high comsumption Message.

Could it be that the application tries to display its own message and creates an infinite loop because I've disabled all notifications of this application? I don't want to have too many symbols in the task bar that's why I've disabled notifications.

Could it be possible to implement the feature for enabling or disabling the status bar notifications of your app?

**Comment by IngoZenz** [comment]
Android is doing this notification stuff internally when a service is started in forground mode. There is not much to develope there.
Do you have issues with other apps as well? I think I will make this configurabe in future versions.

**Comment by tioannidis** [comment]
interesting...the same "high battery comsumption" info with OpenVPN when I disable the OpenVPN-Notification from the status bar. looks like an Android "bug". 

Pool Request: it would be cool if you make this configurable in the future versions :-)
