### ISSUE TITLE
[Bug] in ver 1.50.32.1 

### ISSUE THREAD

**Issue by baraa272** [IngoZenz/personaldnsfilter#34]
Hi and greetings 
I'm a user of your amazing program 
Anyway upon upgrading to latest version 1.50.32.1 and restoration of my backup of previous version
I encountered such a terrible problem 
The dnsfilter was blocking everything 
Blocking every connection 
I thought it might be my filterlists fault but still after disabling all my filters and make sure the index is 0 still the dnsfilter blocking everything
I tried to reset the whole program but still was blocking everything 
I backed up to the previous version 1.50.31 as it was working well for me 
So it might be not an big issue but it would be great if you looked at it 
My device is s7 edge sm-g935 exynous 
Ps. I downloaded the latest apk from f-droid

**Comment by IngoZenz** [comment]
Could be related to wildcard blocking coming with version 1.50.32.
Do you have a * in affitionalHosts?

**Comment by IngoZenz** [comment]
@baraa272  any update? Is the issue solved for you?

**Comment by IngoZenz** [comment]
I am closing this as I did not receive any more info here
