### ISSUE TITLE
PersonalDNSfilter blocks all traffic.

### ISSUE THREAD

**Issue by tuqueque** [IngoZenz/personaldnsfilter#35]
Hello. Last night I tested this program installing it from F-Droid and it seemed like the only program I could use in my old 4.4.2 Android phone to block adds and spam traffic (Since the BlokadaV3 app doesn't run on old Android versions and my phone is not rooted to try other apps)...

The problem is that when I activate PersonalDNSfilter (or just DNSfilter, that's how's called in F-droid), it blocks everything, I can't even receive Whatsapp messages. I haven't dig deeper, but is not good that right out of the box, this program doesn't work how is supposed to...

One little thing that might help, when I turn on PersonalDNSfilter, it throws this warning in the log window:
```
WARNING!: Application whitelisting not supported for Android version below 5.01!
Setting ignored!
```
I really hope to be able to use DNSfilter on my phone, since it would be the only one I could use in old, non-rooted phones. I would certainly highly recommend it to my friends here in my country, where not many people can afford the luxury of newer phones but still want/need to protect their traffic.

Anyway, thank you very much in advance.

**Comment by IngoZenz** [comment]
Usually this should work.
Could you provide the dnsfilter.conf file and the additionalHosts.txt files from the folder PersonalDNSFilter?
BR, Ingo

**Comment by tuqueque** [comment]
Sure, files attached to this comment (zip file)...

If you need more information or maybe you want me to activate the debug log and send it back to you, that shouldn't be a problem.
[2go.zip](https://github.com/IngoZenz/personaldnsfilter/files/3169091/2go.zip)

BTW, my phone is a really crappy Blu Life Play Mini.
https://www.gsmarena.com/blu_life_play_mini-6835.php

Again, thank you for your work!

**Comment by IngoZenz** [comment]
config looks ok.
What is logged in the log view when hosts are blocked? Is it using the VPN at all?

**Comment by IngoZenz** [comment]
@tuqueque Any update on this?

**Comment by Atavic** [comment]
Maybe try to unselect autostart, then start manually and check if it works.

**Comment by tuqueque** [comment]
Hey, sorry for the late reply... I've done several tests with no luck. It blocks my connection. Attached another .zip with a copy/pasted log view and even a screenshot of the VPN connection.
[log.zip](https://github.com/IngoZenz/personaldnsfilter/files/3213648/log.zip)

Again, I might need instructions, but if there's anything else I can do or check to find the problem, feel free to ask. I'm not an expert in fiddling with phones, but I'm fairly tech savvy.

**Comment by tuqueque** [comment]
Hey, sorry for the late reply... I've done several tests with no luck. It blocks my connection. Attached another .zip with a copy/pasted log view and even a screenshot of the VPN connection.
[log.zip](https://github.com/IngoZenz/personaldnsfilter/files/3213648/log.zip)

Again, I might need instructions, but if there's anything else I can do or check to find the problem, feel free to ask. I'm not an expert in fiddling with phones, but I'm fairly tech savvy.

**Comment by IngoZenz** [comment]
The log shows that the connection to the upstream dns server 1.1.1.1  fails. 
Is this always the case? Is it the same when trying with the default settings and using the DNS server of the ISP? Is the Network generally up?
Could you post your dnsfilter.conf file?

**Comment by IngoZenz** [comment]
in addition to my points above you could also try with 1.50.29 (https://f-droid.org/repo/dnsfilter.android_1502900.apk).
There was a change in between which might have caused this issue on some devices - however so far I did not receive similar issues.

**Comment by IngoZenz** [comment]
As you did not answer anymore I'll close this ticket - seems it is solved for you...
