### ISSUE TITLE
Option to see full urls in logger

### ISSUE THREAD

**Issue by TomJansen** [IngoZenz/personaldnsfilter#38]
Hi! Thanks for your lightweight and fast app. I really like the logger functionality and it would even be more usefull if it printed full urls instead of only the domain. Would that be possible? ( if the view gets too cluttered maybe implement it so that the domain expands into the full url when tapping it?)

**Comment by IngoZenz** [comment]
pDNSf is a DNS based filter and  filters based on the DNS requests. On this level there is no URL. So it is not possible.
