### ISSUE TITLE
Add support for Dohnut DoH

### ISSUE THREAD

**Issue by sivajipro** [IngoZenz/personaldnsfilter#39]
https://github.com/commonshost/dohnut/blob/master/README.md

**Comment by IngoZenz** [comment]
Could you provide more details about what is missing?

**Comment by sivajipro** [comment]
I dont know what is missing. But it wont work with pDNSf. I thought pDNSf support DoH.

**Comment by IngoZenz** [comment]
Please post the configuration and the error you receive.

Thanks!

Regards, Ingo

**Comment by sivajipro** [comment]
Config: 139.162.131.245::443::DoH::https://commons.host


****This is personalDNSfilter V+1.50.32****

Initializing ...
***Initializing PersonalDNSFilter Version 1.50.32!***
Using Directory: /storage/emulated/0/PersonalDNSFilter/
Using Blocking Mode!
VPN Connected!
DNS Filter: Next filter reload:Sun Jun 16 18:36:21 GMT+08:00 2019
VPN Runner Thread 1 started!
DoH failed for https://commons.host! 505 - HTTP/1.1 505 HTTP Version Not Supported
IO Error occured! Check network or DNS Config!

**Comment by IngoZenz** [comment]
The problem seems that commons hosts only support HTTP /2 for doh.
Unfortunately HTTP/2 is not yet supported by the Android SDK. As far as I know thjis will be supported with Android 10 only.
You migtht ask the donat folks to open doh for HTTP/1.1 as well. All major providers do this.

**Comment by sivajipro** [comment]
Ok. Thank you.
