### ISSUE TITLE
Force close with Lollipop 5.0.2 [personalDNSfilter 1.50.17] 

### ISSUE THREAD

**Issue by fds39** [IngoZenz/personaldnsfilter#4]
Hi IngoZenz,

Thanks for your really smart app.
I suffer random crashes with personalDNSfilter 1.50.17 version. I reinstalled from scratch LG G2 d802 stock rom with lollipop 5.0.2

Unfortunately it didn't change anything. So here's a catlog that recorded the last FC. Forgive me if the wording of my question is not quite standard : as a n00b I hope I will be able to help you fixing this issue.

I have already posted some questions to t-ryder on this thread https://forum.xda-developers.com/android/apps-games/app-personaldnsfilter-block-malware-t3567898/page5

[2018-06-10-14-25-09_DNSFilter_ForceClose.txt](https://github.com/IngoZenz/personaldnsfilter/files/2087940/2018-06-10-14-25-09_DNSFilter_ForceClose.txt)

**Comment by IngoZenz** [comment]
Hi, thanks for reporting this! The trace is helpfull. Is this for the original APP vor theRB Version?

**Comment by fds39** [comment]
This one http://zenz-solutions.de/personaldnsfilter/

If you want me to test on another version, just tell me; to avoid any confusion, please indicate the direct link

**Comment by fds39** [comment]
Good morning Ingo,

Thank you for your diligent involvement

For the first time, the application was still active after one night. Unfortunately the application crashed when opening the browser, so I restarted a catlog at 6:00 am at the same time as personalDNSfilter (1.50.18-dev). after ~2 hours, not seeing any crash, I decided to change my connection: wifi >> data (4g)

At 8h08, the crash occurred.

I hope I didn't shorten the log too much :

[2018-06-11-06-02-46.txt](https://github.com/IngoZenz/personaldnsfilter/files/2088911/2018-06-11-06-02-46.txt)

**Comment by IngoZenz** [comment]
Thanks again...

It is still the same problem ... I will continue to investigate this and let you know once there is an update.

 

 

 

 

Gesendet: Montag, 11. Juni 2018 um 08:45 Uhr
Von: fds39 <notifications@github.com>
An: IngoZenz/personaldnsfilter <personaldnsfilter@noreply.github.com>
Cc: IngoZenz <i.z@gmx.net>, Comment <comment@noreply.github.com>
Betreff: Re: [IngoZenz/personaldnsfilter] Force close with Lollipop 5.0.2 [personalDNSfilter 1.50.17] (#4)


Good morning Ingo,

Thank you for your diligent involvement

For the first time, the application was still active after one night. Unfortunately the application crashed when opening the browser, so I restarted a catlog at 6:00 am at the same time as personalDNSfilter (1.50.18-dev). after ~2 hours, not seeing any crash, I decided to change my connection: wifi >> data (4g)

At 8h08, the crash occurred.

I hope I didn't shorten the log too much :

2018-06-11-06-02-46.txt

**Comment by IngoZenz** [comment]
I still do not understand how the issue could happen here. I also can't reproduce it on my devices.
However I have submitted a workarround to the dev branch which should fix the issue.
Please try https://github.com/IngoZenz/personaldnsfilter/releases/download/1.50.18-dev/app-1.50.18-dev-02.apk and let me know if this works for you.

**Comment by fds39** [comment]
Hello Ingo,

Good news this morning, I think this last version does the trick. After almost 20 hours of testing, still no FC
Last night I even installed Smart Network (Xposed) to test the automatic triggers (GPS, data, wifi, sync). Working so fine now :)

I would like to take advantage of this exchange to know if you could also implement this fix in the [AdZHosts.apk](https://adzhosts.fr/apk/AdZHosts.apk) fork which is my favorite tool (thanks to Hajdar its dedicated author)

Finally forgive this off-topic, I use a lot the USB tethering mode to access internet with my laptop. I have observed the filtered or allowed traffic in the personalDNSfilter window: nothing seems to be filtered when smartphone is connected to my PC. Have you considered an option to filter traffic in tethering mode?

Regards
FS

**Comment by IngoZenz** [comment]
Good news!

I will include the fix in the next release and also merge it into the AdzHosts branch...

It might take a couple of days...

Regards, Ingo

 

Gesendet: Dienstag, 12. Juni 2018 um 09:37 Uhr
Von: fds39 <notifications@github.com>
An: IngoZenz/personaldnsfilter <personaldnsfilter@noreply.github.com>
Cc: IngoZenz <i.z@gmx.net>, Comment <comment@noreply.github.com>
Betreff: Re: [IngoZenz/personaldnsfilter] Force close with Lollipop 5.0.2 [personalDNSfilter 1.50.17] (#4)


Hello Ingo,

Good news this morning, I think this last version does the trick. After almost 20 hours of testing, still no FC
Last night I even installed Smart Network (Xposed) to test the automatic triggers (GPS, data, wifi, sync). Working so fine now :)

I would like to take advantage of this exchange to know if you could also implement this fix in the AdZHosts.apk fork which is my favorite tool (thanks to Hajdar its dedicated author)

Finally forgive this off-topic, I use a lot the USB tethering mode to access internet with my laptop. I have observed the filtered or allowed traffic in the personalDNSfilter window: nothing seems to be filtered when smartphone is connected to my PC. Have you considered an option to filter traffic in tethering mode?

Regards
FS

**Comment by IngoZenz** [comment]
version 1.50.18 ist released and fixes the issue.
default version: http://www.zenz-solutions.de/personaldnsfilter/getAPK.php
AdZHosts version: http://www.zenz-solutions.de/personaldnsfilter/getAdzHostsAPK.php
