### ISSUE TITLE
Color blind mode for the log.

### ISSUE THREAD

**Issue by Kezxo** [IngoZenz/personaldnsfilter#40]
I am somewhat color deficient he red and green colors for allowed and blocked hosts can be problematic sometimes, I actually really like that the log has such small font except the colors make it harder to parse. I know there are checkboxes and X's on the side but it's not that fun to always look back and forth between them and the host name.

Alternatively change the background of the text instead of the characters to make it more readable for different color deficiencies, making out colors of tiny text is harder than the backgrounds.

If you want to see how colors can be a problem and you use windows 10 to develop the app then try to use the Win+Ctrl+C shortcut to make your screen temporarily greyscale.

**Comment by IngoZenz** [comment]
Thanks for the feedback. I will see what I can do in one of the next versions...
Greetings, Ingo

**Comment by IngoZenz** [comment]
This is what I plan to offer for the next release.
You can configure some log format within the dnsfilter.conf file.

Hope this helps!

```
#log colors and text size (Android only)

filterLogFormat = <font color='#D03D06'>($CONTENT)</font>
acceptLogFormat = <font color='#23751C'>($CONTENT)</font>
normalLogFormat = ($CONTENT)
logTextSize = 14
```
You can set the log format via HTML and you can set teh log test size (14 is current default)
[DNSFilter-1.50.34.0-dev.apk.zip](https://github.com/IngoZenz/personaldnsfilter/files/3609966/DNSFilter-1.50.34.0-dev.apk.zip)

Does this help?

**Comment by Kezxo** [comment]
That sounds great, thanks for adding this!
Only issue might be that editing a conf file might be a bit cumbersome for some people but this sure is way better than before, I can handle it for sure.

**Comment by IngoZenz** [comment]
Released with https://github.com/IngoZenz/personaldnsfilter/releases/tag/1.50.34.3
