### ISSUE TITLE
is it possible to redirect specific domains to a different IP

### ISSUE THREAD

**Issue by Nirose** [IngoZenz/personaldnsfilter#41]
Is it possible to redirect domains to a different IP than the one set by upstream DNS provider?

For example:
specificdomain.com -> 192.168.1.55
cdn.specificdomain.com -> 123.123.123.123

is this possible with the dnsconf file?

Thanks

**Comment by Atavic** [comment]
That's done by an http proxy.

**Comment by IngoZenz** [comment]
personalDNSfilter does not support this - it only redirects filtered hosts to loopback. What is the use case?

**Comment by Nirose** [comment]
use it like the host file in the operating system. so you can redirect DNS requests of some domain to a local address or a different IP.

**Comment by IngoZenz** [comment]
that's not the scope of pDNSf as it is a DNSFilter -  so it does not really fit as feature. However if there isn't the plan to add thousands of redirects, it could be implemented in a straightforward - non-sophisticated manner.
On the other side it could be a security issue as well ...

**Comment by Nirose** [comment]
I understand. no cynical intentions at all. haha

i was thinking something like adding static entries in Linux dnsmasq.d:

server=/local.lan/192.168.1.1

why do you think it could be a security issue?

**Comment by IngoZenz** [comment]
It could be a security issue because in case an attacker could create such a redirect file, the attacker could redirect your traffic to his servers and spy your passwords, etc...

**Comment by Nirose** [comment]
hmm... but that would require physical access and unlocking the phone. wouldn't it? at that point everything should be considered compromised.

An malicious app could create such a file with storage permission but it's unlikely as it would need to know if the app is running with app usage permission or accessibility access. 

I just think it would be a nice option. i use pi-hole at home but I don't want to VPN to it from my phone when not in the home network as adblocking can be done with light app like DNSFilter.

**Comment by IngoZenz** [comment]
Ok...I'll consider this...

**Comment by Nirose** [comment]
Thank you so much. :)

**Comment by IngoZenz** [comment]
Btw: Might be Pi-Hole is currently the better alternative for the home network as it is dedicated to t and optimized for use case.  But are you aware that pDNSf can also run in the home network on PC or raspberry or s.th. else? 
With the next version it will be possible to manage such an instance remote from the Android app :-)

**Comment by IngoZenz** [comment]
This is now  available in version 1.50.46.
