### ISSUE TITLE
Feature Request: Allow to add alternative DoT domain name

### ISSUE THREAD

**Issue by kowith337** [IngoZenz/personaldnsfilter#42]
I wish to suggest to expand config for DoT resolver where some DoT DNS service have more than one domain but still have one or same IP address.

For example, [SecureDNS](https://securedns.eu) have one IP address, but two DoT resolver domains below.
- `dot.securedns.eu`
- `ads-dot.securedns.eu`

An existing DoT config entry is...
- `146.185.167.43::853::DoT`

The improved DoT config entry will be like...
- `146.185.167.43::853::DoT::dot.securedns.eu`
- `146.185.167.43::853::DoT::ads-dot.securedns.eu`

**Comment by IngoZenz** [comment]
Can't you just add both entries to the DNS config? It will switch in case one gets unavailable

**Comment by kowith337** [comment]
It seems like it's supported.

But I have no idea due to no example provided to know that it's already supported.

Thanks anyway.

**Comment by opusforlife2** [comment]
@IngoZenz Can this be added to the default examples so that users can know?

**Comment by IngoZenz** [comment]
Good Point :-)

**Comment by IngoZenz** [comment]
https://github.com/IngoZenz/personaldnsfilter/commit/4bb8586c2cb9af6de96faddfafbdf6cbb567c35c

**Comment by opusforlife2** [comment]
@IngoZenz Could you include both the examples? With and without the domain, so that the user knows both are valid configurations?

**Comment by IngoZenz** [comment]
see https://github.com/IngoZenz/personaldnsfilter/commit/35e5f5e65b0bab1c16115d85d45b6b13f277013e
