### ISSUE TITLE
[Bug] Crash when trying to copy text from the logs area

### ISSUE THREAD

**Issue by SnwMds** [IngoZenz/personaldnsfilter#44]
**Steps to reproduce:**

1. Open PersonalDNSFilter
2. Select an random text from the logs area
3. Try copying everything, including the area that not contains text
4. See the crash

The crash basically occurs when the user try to copy the text from an area that doesn't contains it (out of the area).

**Examples:**

If you try to select a specified text area, the crash doesn't occur:

_[PersonalDNSFilter.png](http://snwmds.org/images/PersonalDNSFilter.png)_ (26.83 KiB)

If you try to copy the "text" from an area where there is none, the crash occurs:

_[PersonalDNSFilter.mp4](http://snwmds.org/videos/PersonalDNSFilter.mp4)_ (3.63 MiB)

**Logs:**

System logcat, crash log, event logs and main logs:

_[PersonalDNSFilter.zip](http://snwmds.org/dl/PersonalDNSFilter.zip)_ (10.96 KiB)

**Environment:**

Device: `AllCall S1 X`  
Manufacturer: `Teksun`  
ROM: `Android 8.1 Stock/Unmodified (armv7)`

PersonalDNSFilter version: `1.50.33.5`

**Comment by IngoZenz** [comment]
Thanks for the detailed analysis.
It is fixed in dev with https://github.com/IngoZenz/personaldnsfilter/commit/18acfbe10cc59dc63cad99ff4dbf90686a239a12.
[DNSFilter-1.50.33.6-dev.zip](https://github.com/IngoZenz/personaldnsfilter/files/3588956/DNSFilter-1.50.33.6-dev.zip)

**Comment by SnwMds** [comment]
Thanks for the quick response and for solving the problem quickly, @IngoZenz.

I tested the version that you have sent. Everything is working fine.
