### ISSUE TITLE
Feature Request: OpenVPN support

### ISSUE THREAD

**Issue by sathish804** [IngoZenz/personaldnsfilter#45]
Hi,

Please consider adding OpenVPN support in pDNSf , it would be a great option to use a pro VPN account with OpenVPN support along side the local DNS ad filtering.

Thanks and Regards,
Sathish.

**Comment by IngoZenz** [comment]
I fear this will only be possible on a rooted device.

You would need to run pDNSf in DNS Proxy mode (required root) and configure your VPN client to use 127.0.0.1 for DNS resolution.

**Comment by IngoZenz** [comment]
as described above - this is already possible as of today with running in proxy mode on a rooted device

**Comment by sathish804** [comment]
Thank You!!

**Comment by sathish804** [comment]
IngoZenz Good day!! I was searching for any available Local AdBlock VPN's along side the Premium VPN services. I found Blokda which is offering this feature and Blokda not need root privileges to work.  Thought of sharing the info with you which might help you to implement the OpenVPN support in pDnsF. 

https://github.com/blokadaorg/blokada

**Comment by IngoZenz** [comment]
there is a dev version available which can run without the dummy vpn on rooted android and which can be combined with real VPN like android. 

Feel free to join us at https://telegram.me/pdnsf

**Comment by IngoZenz** [comment]
fixed with https://github.com/IngoZenz/ics-openvpn#openvpn-for-personaldnsfilter
