### ISSUE TITLE
Android 10 or Cloudflare Oddity

### ISSUE THREAD

**Issue by mwsasser** [IngoZenz/personaldnsfilter#47]
After updating to the Android 10 Sept 5 Security Patch, I had a weird error originating from the operating system.  Sorry that I cannot recall the exact wording.  However it suggested that V1.50.31 wasn't compatible with this version of Android.

At the time I had installed Cloudflare's new VPN app but never tested it.  Every time I tried to enable blocking, the phone would make a "ding ding ding" audio sound but no other message.  

PersonalDNSFilter did not allow any network traffic at that time.

Uninstalling the Cloudflare app didn't help but then rebooting "seems" to have stopped the error message and "ding" sounds.

No entirely sure of what why it happened.  But you guys might find it useful in some way.

UPDATE:

After updating to Version 1.50.33.5, I've tested again.  My phone doesn't seem to work well if your app is active.  The log isn't showing network activity when I try to use apps.

My phone is a Pixel 3 XL with Android 10, Sept 5 Security Patch.

**Comment by IngoZenz** [comment]
Will need to check with Android 10

**Comment by mwsasser** [comment]
Any way I can send you test data?

**Comment by IngoZenz** [comment]
Thank you! Will let you know once I got the time to test with Android 10...

**Comment by toufou54** [comment]
Same for me, just updated to Android 10 on OnePlus 7 pro: no networking access with dnsfliter active

**Comment by IngoZenz** [comment]
Still didn't get the chance and time to test with android 10

**Comment by c-rilaun** [comment]
No issue with Android 10 on my side (except some UI improvement needed).

**Comment by mwsasser** [comment]
It's still not working on my Pixel 3 XL.  We've had a couple of security patches since my original post.  If I turn the app on, it still loses internet access.

**Comment by c-rilaun** [comment]
> If I turn the app on, it still loses internet access.

You mean, you have no internet connection over all of your phone ? 
What are your DNS settings ? 

I attach my DNS seetings:
[personalDNSfilter.txt](https://github.com/IngoZenz/personaldnsfilter/files/3845984/personalDNSfilter.txt)

What are your filters ? 

_Don't forget that you are using something which request to get your hands a lil bit dirty. This is not for common user, you need to have some knowledge._

**Comment by IngoZenz** [comment]
what is displayed in the log view when internet access fails?

**Comment by mwsasser** [comment]
Sorry for the delay.  Hope this helps.
![Screenshot_20191119-081040](https://user-images.githubusercontent.com/7670483/69154607-e66ce800-0aa5-11ea-9584-9b817da69189.png)

**Comment by IngoZenz** [comment]
This error occurs when you touch the remote control button and remote control is not configured.
Looking to the green log entries it also looks like the DNS forwarding is working,,,

**Comment by mwsasser** [comment]
All I can tell you, is that when I Enable Blocking.  All internet stops.

**Comment by IngoZenz** [comment]
any more logs within the log view  when internet is not working?

**Comment by IngoZenz** [comment]
There is no general issue on Android 10.
I am closing this ... you might provide additional logs and reopen in case you still face the issue
