### ISSUE TITLE
Building in AndroidStudio fails.

### ISSUE THREAD

**Issue by ChefTyler** [IngoZenz/personaldnsfilter#48]
The current build.gradle fails, this is how I fixed it.
`
buildscript {
    repositories {
        google() // here
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}
allprojects {
    repositories {
        google() // and here
        jcenter()
    }
}
`

**Comment by IngoZenz** [comment]
means you have removed jcenter repo?
But usually it should work and it might be required. What was the error?

**Comment by ChefTyler** [comment]
'''Could not find com.android.tools.build:aapt2:3.5.0-5435860.
Searched in the following locations:
  - https://jcenter.bintray.com/com/android/tools/build/aapt2/3.5.0-5435860/aapt2-3.5.0-5435860.pom
  - https://jcenter.bintray.com/com/android/tools/build/aapt2/3.5.0-5435860/aapt2-3.5.0-5435860-linux.jar
Required by:
    project :app'''
As you can see the domains 404 now.
There is also the issue of the TargetSdkVersion 'As of the second half of 2018, Google Play requires that new apps and app updates target API level 26 or higher'

**Comment by IngoZenz** [comment]
will check... 
Existing Project builds fine for me but I assume I have to build from scratch.
With TargetDdkVersion  we need to see what is the impact.
We also want still to support Android 4 ;-)
Playstore anyhow doesn't want apps like mine...

**Comment by IngoZenz** [comment]
I have just started from scratch - cloned the project and imported it into Android Studio => No issue for me! Be sure you import the project after cloning and not just to open it...
