### ISSUE TITLE
Chrome on android 9

### ISSUE THREAD

**Issue by netgrouppanama** [IngoZenz/personaldnsfilter#49]
Hi, this personal dns filter is great!
Ive used on android 6 to android 8 phones, I just got a new phone Galaxy A30(Android 9), the filter still works but not for chrome or samsung browser, (chrome beta doesnt work either), it works on firefox and other browsers, is there a way to fix this, maybe some configuration?

**Comment by kowith337** [comment]
In Chrome or any forks [e.g. Brave, Vivaldi, Opera (not sure)]

Have you toggle `#enable-async-dns` to disable in `chrome://flags` ?

Instruction: https://github.com/ookangzheng/blahdns/blob/master/FAQ.md#prevent-dns-leaking-from-chrome-browser-on-android-phone

**Comment by IngoZenz** [comment]
yes - in fact with this async dns feature chrome ignores /bypasses the system DNS - very bad practice in my opinion

**Comment by kowith337** [comment]
Personally, I'm also aware about `Chrome` and maybe also WebView, since Android 6+ can (force) use `Google Chrome` itself for WebView replacement.

> - If users didn't disable Google Chrome.
> - Also count Beta, Dev and Canary, too, if you've installed them.

And also, Android 10 will also bundling both Chrome and WebView together via `TriChrome` and may impossible to divide.

**Comment by netgrouppanama** [comment]
Thanks Kowith, disabling sync dnd worked👍 but still trying to find another way.

Thaks IngoZens for this App.

**Comment by netgrouppanama** [comment]
BTW I found out that if you add a custom private dns on android 9 then chrome and samsung internet and other apps(like google app) dont bypass the vpn dns.

**Comment by mobisecitalia** [comment]
> BTW I found out that if you add a custom private dns on android 9 then chrome and samsung internet and other apps(like google app) dont bypass the vpn dns.

Is possible to set it programmatically?

**Comment by IngoZenz** [comment]
I fear there is nothing I can do here so I am closing this.
Interferring whole network traffic is not in scope for the app and also not good for Battery
