### ISSUE TITLE
Packet Capture Issue on Opera Browser

### ISSUE THREAD

**Issue by AsifNazir** [IngoZenz/personaldnsfilter#5]
Hi,

I have noticed that when i install personaldnsfilter on android phone having OS version 7.1.2 N2G47H. It is showing blocked domains when i use chrome, UC browsers but when i open Opera Mini Browser & open blocked domain, it is NOT capturing network traffic and blocking domain

Is there any open issue with Opera Browser ?

**Comment by AsifNazir** [comment]
Secondly how can i check captured traffic is SSL or NOT ?

**Comment by IngoZenz** [comment]
Opera does not use the System DNS by default which in my opinion is bad behaviour. It redirects all traffic to some proxy server on which the DNS Resolution takes place.
You need to switch off the "turbo mode" in Opera. 
See https://superuser.com/questions/808377/how-to-make-opera-browser-obey-the-etc-hosts-file.

Regarding SSL: SLL is filtered as well as all other protocolls. personalDNSfilter is a hosts based filter Independent on the used protocoll. It also does not watch the traffic.

**Comment by AsifNazir** [comment]
Thanks 

i have also noticed that ip only pages are not captured in application. How do we block them.

**Comment by IngoZenz** [comment]
This is a DNS filter which blocks domain name resolution (Hostname to IP). For "ip only" a DNS is not used, means not possible via this tool.
