### ISSUE TITLE
Image filtering

### ISSUE THREAD

**Issue by AviFix** [IngoZenz/personaldnsfilter#51]
Hi,

Thanks for this great project.

I'm looking for a way to filter images.

Will it be possible to block only image file from getting downloaded to the device?

Thanks

**Comment by kowith337** [comment]
I don't think it's possible, this app is just DNS + Hosts file based blocking, it's mean to block domains or whole domains if you've add to your additional hosts.

**Comment by IngoZenz** [comment]
Sorry but it is not possible via DNS filtering
