### ISSUE TITLE
v1503403 is broken and doesn't correctly pick up DNS from DHCP

### ISSUE THREAD

**Issue by ckuethe** [IngoZenz/personaldnsfilter#53]
I just upgraded to 1503403 from 1503305 and pdnsfilter no longer picks up DNS resolvers correctly after switching networks.

I rebooted my phone and pdnsfilter didn't see the carrier provided DNS, though it was able to use manually specified DNS resolvers. This is not acceptable since some networks require that I use the internal DHCP-specified resolvers.

Reverting to 1503305 makes the problem go away. Let me know if there is any particular debug info that would be helpful.

Samsung Galaxy S9+, Android 9

**Comment by IngoZenz** [comment]
Ah yes - it is because of the switch to the new target version 28...
Here Android does not support DNS Server retrieval via the System Properties anymore.
https://developer.android.com/about/versions/oreo/android-8.0-changes.html#o-pri.
Will fix this soon...

**Comment by IngoZenz** [comment]
should be fixed with v1503404
[dnsfilter-1503404.zip](https://github.com/IngoZenz/personaldnsfilter/files/3923195/dnsfilter-1503404.zip)

**Comment by IngoZenz** [comment]
https://github.com/IngoZenz/personaldnsfilter/releases/tag/1.50.34.4
