### ISSUE TITLE
How can I filter/block all websites except some domains?

### ISSUE THREAD

**Issue by abozanona** [IngoZenz/personaldnsfilter#57]
How can I prevent access to all websites excepts for a specific list of domains `www.domain-1.com`,  `www.domain-2.com`, `www.domain-3.com`,,, `www.domain-n.com`?

Users must only access those specific list of domains.

**Comment by IngoZenz** [comment]
usually by additing the following to additional hosts:
```
*
!www.domain-2.com
!www.domain-3.com
...
 !www.domain-n.com

```
However currently released version contains a bug which will cause that the whitelisted domains get blocked by theit IP Address - I think a fix will be released in comming days.

Either wait for this or use the current dev version:
[dnsfilter-1503405-dev04.zip](https://github.com/IngoZenz/personaldnsfilter/files/3988578/dnsfilter-1503405-dev04.zip)

**Comment by IngoZenz** [comment]
The whitelisting as described above is working again in current version. 
So just add the * filter and whitelist as described above
