### ISSUE TITLE
Websites are not blocked on devices connected to my wifi hotspot

### ISSUE THREAD

**Issue by abozanona** [IngoZenz/personaldnsfilter#58]
I filtered a website on my device(Device A) `www.example.com` and I was successfully unable to open it from the browser.
I created a HotSpot wifi and connected another device(Device B) to the WiFi network created by (Device A). When I open the filtered website `www.example.com` on (Device B) it's not filtered.
How can I apply the filter rules on all the devices connected to the HotSpot I created?

**Comment by IngoZenz** [comment]
Wifi Hotspot does not use the VPN.
In case you have a rooted phone, start pDNSf in dns proxy mode and configure device B to use Device A as DNS Server

**Comment by abozanona** [comment]
Hi @IngoZenz 
Thanks for help.
Could you please tell me how can I start the application in `dns proxy mode`? And How can I configure device `B` to use the current device as DNS server?

**Comment by IngoZenz** [comment]
in <storage>/personalDNSfilter you'll find a config file "dnsfilter.conf".

```
# dnsProxyOnAndroid = true|false - used  by Android version.
# if true, on Android in addition to VPN Service, a DNS Proxy is started (requires root!)
# Could act as DNS filter Proxy within the local network.
dnsProxyOnAndroid = false
```
Regarding Q2 - it is OS specific.

Bets woudl be if Android would support that you configure the DNS Server as part of the hot spot config ...
