### ISSUE TITLE
problem with signal app

### ISSUE THREAD

**Issue by yokgit** [IngoZenz/personaldnsfilter#60]
hi,
when using with Signal app, voice call won't work at all. only notifies  you had a missed call. whitelist signal solves it.
using both latest apps.
  thanks

**Comment by IngoZenz** [comment]
Alternativly for app whitelisting you might try to find out via the "x red" log entries which host makes the problem and whitelist it.
Also feel free to join our TG channel to discuss the problem there.

**Comment by IngoZenz** [comment]
No more feedback from reporter =close
