### ISSUE TITLE
App doesn't start on boot on Android 10

### ISSUE THREAD

**Issue by Sayueri** [IngoZenz/personaldnsfilter#61]
I have a Nokia 7.1 running android 10. Personaldnsfilter attempts to start on boot but crashes. Even with Always VPN on, I have to open it manually for it to work.

Also, since upgrading to 10, I get "Your connection was interrupted. A network error was detected." messages in Chrome with Personaldnsfilter on. Websites will still load but I get that message each time I open a site for the first time. This doesn't happen with DuckDuckGo, Firefox, Edge or Opera. Only Chrome.

**Comment by IngoZenz** [comment]
Do you have some error log in the log view after autostart?

**Comment by Sayueri** [comment]
No. I don't have an error log. There's only a traffic log. After further inspection, it looks like the app is running on startup with Always VPN on and blocking ads. My phone shows the "Device is connected to DNSFilterService" notification. Without Always VPN on, it doesn't start up or block ads even though its set to Autostart.

The strange thing is when I try to open the app for the first time after boot, the app will close on me. The next time I open the app it opens normally. From that point on, everything is fine. It's only on boot that's the issue.

Below is what I see in the content box once I'm able to open the app.

---------

****This is personalDNSfilter V+1503600****

Initializing ...
Running on SDK29
DNSFilter stopped!
VPN Runner Thread 1 terminated!
DNS Filter: AutoFilterUpdater stopped!
***Initializing PersonalDNSFilter Version 1503600!***
Using Directory:
Aquired WIFI lock and partial wake lock!
Released WIFI lock and partial wake lock!
Using Blocking Mode!
VPN Connected!
DNS Filter: Next filter reload:
VPN Runner Thread 2 started!

------------

**Comment by IngoZenz** [comment]
Thanks for the update!
Could you install my current dev version which produces additional dump files in case of crashes?
After the crash, please post the dump file from the personalDNSfiler folder.


[dnsfilter-1503601-dev.zip](https://github.com/IngoZenz/personaldnsfilter/files/4025597/dnsfilter-1503601-dev.zip)

**Comment by IngoZenz** [comment]
fix with https://github.com/IngoZenz/personaldnsfilter/releases/tag/1.50.37.0
