### ISSUE TITLE
App crash on Android 9 with December security patches

### ISSUE THREAD

**Issue by Stark2x** [IngoZenz/personaldnsfilter#62]
Following the installation of the December security updates on a BQ Aquaris X2 (zangya) device, DNSfilter started crashing on startup. I am not sure it is related to the December security patches, but all other device running DNSfilter do not have any problems.

Crash log, showing a ArrayIndexOutOfBoundsException, can be found [here](https://pastebin.com/7U2XkUB8).

**Comment by IngoZenz** [comment]
The ArrayIndexOutOfBoundsException is comming from Android Code itself...
This looks like an Android bug to me

**Comment by IngoZenz** [comment]
search Google for

`"at android.text.TextLine.draw(TextLine.java:267)"`

You'll find the issue also for other apps - so really seems Android bug

**Comment by Stark2x** [comment]
Thanks for looking into it.

I guess I can close this issue then.
