### ISSUE TITLE
DNS redirect does not work

### ISSUE THREAD

**Issue by Kein** [IngoZenz/personaldnsfilter#65]
I have DNScrypt-proxy running on 127.0.0.1:9053
I have disabled DNS discovery and set up manual DNS server with custom port in the DNS list
127.0.0.1::9053::UDP

However, pDNS never sends any DNS question to DNScrypt-proxy.
Android 10, device isnt rooted

**Comment by IngoZenz** [comment]
Any logs?
Best would be to discuss the issue in our tg group https://telegram.me/pdnsf.
There many experienced users willing to help!

**Comment by Kein** [comment]
Dont use telegram.
Logs are fine:

> Initializing personalDNSfilter...
> Using directory /storage/emulated/blabla
> Using blocking mode
> VPN Connected
> VPN Runner thread 5

I see no dns-queries in DNscrypt-proxy and shutting it down has no effect on name resolution capabilities. It would appears pDNSf still uses its own DNS servers. May be it is the filter-list stuff that affects it? Any idea how can I COMPLETELY disable any filters and lists and dynamic stuff and force it to work ONLY in relay mode to local DNS server?

**Comment by Kein** [comment]
Closing this issue because it works now for no apparent reason after a reboot. I havent changed anything at all and it seems to be more or less working.

My previous question still remains though: **how can I COMPLETELY disable any filters and lists and dynamic stuff and force it to work ONLY in relay mode to local DNS server?**

**Comment by IngoZenz** [comment]
I think disabling the "Activate Blocker" option  should do the job...
