### ISSUE TITLE
Android 9 Issues

### ISSUE THREAD

**Issue by AhmadKamboh786** [IngoZenz/personaldnsfilter#67]
I hope you are well!
Your  work is fabulous!
I am facing an issue in android 9.
the filter is not works for chrome. can you please provide me the solution or fix for that problem?

**Comment by kowith337** [comment]
Duplicate to #49, please also see instruction about turning off `async-dns`

**Comment by AhmadKamboh786** [comment]
@kowith337  how i can off async-dns programmatically??

**Comment by kowith337** [comment]
It's chrome out-of-box settings and you need to dive in `chrome://flags`, then find the `#enable-async-dns` flag and turn it off.

Or else, try looking for the good fork like [Bromite](https://bromite.org) or [Marmaduke's](https://github.com/macchrome/droidchrome) Chromium that set to turn off `async-dns` by default.

**Comment by AhmadKamboh786** [comment]
Bypass VPN
Your VPN can allow apps to bypass the VPN and select their own network. To bypass the VPN, call VpnService.Builder.allowBypass() when establishing a VPN interface. You can’t change this value after you start your VPN service. If an app doesn’t bind their process or a socket to a specific network, the app’s network traffic continues through the VPN.

Apps that bind to a specific network don’t have a connection when somebody blocks traffic that doesn't go through the VPN. To send traffic through a specific network, apps call methods, such as ConnectivityManager.bindProcessToNetwork() or Network.bindSocket() before connecting the socket.

**Comment by AhmadKamboh786** [comment]
> It's chrome out-of-box settings and you need to dive in `chrome://flags`, then find the `#enable-async-dns` flag and turn it off.
> 
> Or else, try looking for the good fork like [Bromite](https://bromite.org) or [Marmaduke's](https://github.com/macchrome/droidchrome) Chromium that set to turn off `async-dns` by default.

@IngoZenz
@kowith337
Please tell me by this process can we get google chrome Traffic?(Google VPN service documentation)
Bypass VPN
Your VPN can allow apps to bypass the VPN and select their own network. To bypass the VPN, call VpnService.Builder.allowBypass() when establishing a VPN interface. You can’t change this value after you start your VPN service. If an app doesn’t bind their process or a socket to a specific network, the app’s network traffic continues through the VPN.

Apps that bind to a specific network don’t have a connection when somebody blocks traffic that doesn't go through the VPN. To send traffic through a specific network, apps call methods, such as ConnectivityManager.bindProcessToNetwork() or Network.bindSocket() before connecting the socket.

**Comment by IngoZenz** [comment]
Nothing I can do here - so closing...
