### ISSUE TITLE
feature request: block all traffic for some apps

### ISSUE THREAD

**Issue by jawz101** [IngoZenz/personaldnsfilter#69]
It would be nice to be able to simply block all traffic for an app if it can run offline

**Comment by alexanderadam** [comment]
It would stop working for any device that updates to Android 10 _if_ this feature would be implemented.

See also [this comment](https://github.com/blokadaorg/blokada/issues/49#issuecomment-590785458) and [this for a source](https://github.com/julian-klode/dns66/issues/30#issuecomment-590894700).

**Comment by IngoZenz** [comment]
Technically difficult  to realize- not planned
