### ISSUE TITLE
Option to backup filtered host in txt format

### ISSUE THREAD

**Issue by jerryn70** [IngoZenz/personaldnsfilter#7]
Currently we have 3 host source in the app. And app filters this host and remove duplicate entries. So my request is to have an option export the filtered host (host file after duplicate removed) in txt format.

**Comment by IngoZenz** [comment]
Note really sure what would be the benefit of this except to save some small amount of disk space.
Internally pDNSf uses an internal indexed representation of the hosts file. The host file itself is used only once for building this index.

**Comment by jerryn70** [comment]
It helps to view the filtered hosts list

**Comment by IngoZenz** [comment]
For this I suggest to look directly on the hosts files you have configured to be used in pDNSf.

**Comment by d-adi4** [comment]
@jerryn70 you can manual copy paste "FILTERHOSTS.txt" and get the raw format in txt format.

**Comment by jerryn70** [comment]
@d-adi4  that is not a merged list. Check it you will find duplicate entries in it.

**Comment by d-adi4** [comment]
Yeah... I know it has duplicates but it won't gonna bother you that much

**Comment by IngoZenz** [comment]
done with version 1.50.29.
There is a new setting:
_# Store the filter hosts file without duplicates.
# Note: Independent on this setting, pDNSf uses internally a duplicate free index representation.
filterHostsFileRemoveDuplicates = false_
