### ISSUE TITLE
Feature request: allow CNAME Cloaking Protection while not filtering otherwise

### ISSUE THREAD

**Issue by ofiala-a51** [IngoZenz/personaldnsfilter#70]
When whitelisting an app, there should be an option to continue guarding against cname cloaking for that app's connections. This could be useful when whitelisting a browser with addons that block tracking domains, yet don't have access to DNS records (and thus can't guard against cname cloaking).

**Comment by IngoZenz** [comment]
this is technically not possible as an whitelisted app is not catched by pDNSf
