### ISSUE TITLE
Change your openvpn fork name on your build

### ISSUE THREAD

**Issue by Kcchouette** [IngoZenz/personaldnsfilter#71]
Hello
I'm contacting you about your fork [ics-openvpn](https://github.com/IngoZenz/ics-openvpn).
Is it possible that you change the name of your fork, so that we can install openvpn AND your fork on a same device?
Or is it a feature to not do that?

Cheers

**Comment by IngoZenz** [comment]
if it woud be that easy, I would have done it already... 
The project is pretty complex with all the depoendecies etc. 
I think we would need to change the package names - with all dependencies... and make it build...
Unfortunately time is very limitted on my side...

**Comment by IngoZenz** [comment]
decomitted for now
