### ISSUE TITLE
[Bug] Menu items unreachable on small screens

### ISSUE THREAD

**Issue by opusforlife2** [IngoZenz/personaldnsfilter#73]
For example, if you expand Advanced Settings, the bottom few options are cut off by the display edge.

Is it possible to make the menu scrollable?

**Comment by IngoZenz** [comment]
Yes - I am aware and need to fix this - the UI is a bit grown hisorically. I need to rework a bit in order to make that scrollable

**Comment by IngoZenz** [comment]
could you try the dev version- is it workign for you?
[dnsfilter-1503900-dev04.zip](https://github.com/IngoZenz/personaldnsfilter/files/4382276/dnsfilter-1503900-dev04.zip)

**Comment by opusforlife2** [comment]
I don't have access to the small phone I encountered the issue on, but I set my phone's display and font sizes to the maximum, and I can successfully scroll and access all settings. Thanks!

By the way, could you name the package for debug apks differently from the release? Then they could be installed side by side for testing. Also, would it be possible to have the debug apk create a new folder called PersonalDNSFilterDebug or something, so that it doesn't touch the existing folder?

Right now, I had to back up the folder, as well as the app data for the current release, using oandbackup. Then uninstall the release apk and install this one.

**Comment by IngoZenz** [comment]
Unfortunately due to the related effort I can not provide special dev version builds which could be installed side by side. Note that this is free software and I am not payed for this so I can only work on this with limitted prio.
You can always use the backup config feature from within the app.

**Comment by opusforlife2** [comment]
Oh, it's not a massive undertaking, just some changes in the build.gradle. See this one for example: https://github.com/TeamNewPipe/NewPipe/pull/3133/files#diff-39e7d8c00954e920b98e7636f0ac30b2

**Comment by IngoZenz** [comment]
UI issue is closed with latest release 1.50.39.1.
Regarding the debug / dev version seperation - ist hasn't prio for me but will have a look
