### ISSUE TITLE
Android 9.0 chrome Issue Your solution not working

### ISSUE THREAD

**Issue by AhmadKamboh786** [IngoZenz/personaldnsfilter#74]
Hi you have provide this code in DNSFilter service for chrome. But its not working please provide me any programmatically solution. I also check your answer related to android 9 and chrome. But please please provide me programmatically solution. Thanks  

	// add additional IPs to route e.g. for handling application like
		// google chrome bypassing the DNS via own DNS servers
		StringTokenizer additionalRouteIps = new StringTokenizer(DNSFILTER.getConfig().getProperty("routeIPs", ""), ";");
		int cnt = additionalRouteIps.countTokens();
		if (cnt != 0 && Build.VERSION.SDK_INT < 21) {
			cnt = 0;
			Logger.getLogger().logLine("WARNING!: Setting 'routeIPs' not supported for Android version below 5.01!\n Setting ignored!");
		}
		for (int i = 0; i < cnt; i++) {
			String value = additionalRouteIps.nextToken().trim();
			Logger.getLogger().logLine("Additional route IP:" + value);
			try {
				InetAddress adr = InetAddress.getByName(value);
				int prefix = 32;
				if (adr instanceof Inet6Address)
					prefix = 128;
				builder.addRoute(InetAddress.getByName(value), prefix);
			} catch (UnknownHostException e) {
				Logger.getLogger().logException(e);
			}
		}

**Comment by IngoZenz** [comment]
There is nothing I can do - you should disable async DNS in chrome or use another browser.
