### ISSUE TITLE
Chrome issue android 9.0 RESOLVED

### ISSUE THREAD

**Issue by AhmadKamboh786** [IngoZenz/personaldnsfilter#76]
Hi sorry for disturbing you again and again. But i have resolved chrome android 9.0 issue.

builder.addAddress(IPV4, 24).addDnsServer(IPV4Virtual).addRoute("0,0,0,0", 0) ;

By adding addRoute("0,0,0,0", 0)  dns will also capture the chrome traffic. But it show some exception in readDomainName function that you can easily resolved.

**Comment by IngoZenz** [comment]
I think this won't work as pDNSf can only handle DNS traffic. So I think with this route there won't be network anymore.
