### ISSUE TITLE
All downloads are blocked of the stock LineageOS browser and all browsers available at F-Droid

### ISSUE THREAD

**Issue by afonari** [IngoZenz/personaldnsfilter#77]
This is related to: https://github.com/blokadaorg/blokada/issues/209
https://github.com/mozilla-mobile/fenix/issues/2639
https://github.com/julian-klode/dns66/issues/31

**Comment by IngoZenz** [comment]
It is an issue with Android Download Manager in combination with VPN - this cannot be fixed in personalDNSfilter. You only can whitelist the apps having the issue
