### ISSUE TITLE
Cache problem ttl

### ISSUE THREAD

**Issue by nauman404** [IngoZenz/personaldnsfilter#78]
Hi,
I am changing the TTL on the below function in DNS resolver.
 udp.updateHeader(TTL, 17, destination IP, source IP);

It's not reflecting. TTL causes cache in browsers.

**Comment by IngoZenz** [comment]
You are changing TTL on IP layer - that's wrong place. I think the right place would be to change it on the DNS Response layer (DNSResponsePatcher)
