### ISSUE TITLE
pDNSf doesn't ask root

### ISSUE THREAD

**Issue by Revenrof** [IngoZenz/personaldnsfilter#8]
In "dnsfilter.conf" its stated that "dnsProxyOnAndroid" setting need root acces to be enabled. 
However when I change "dnsProxyOnAndroid" from false to true, and then open pDNSf app (I did force stop it before), it doesn't ask for root access. 
And I got this "Exception : Cannot open DNS port 53! bind failed : EACCES ( permission denied)" error message.

**Comment by IngoZenz** [comment]
Thanks for letting me know. This feature "dnsProxyOnAndroid" was not properly tested as I do not have a rooted device. My naiv opinion was that on a rooted device nothing else has to be done and opening port 53 would be possible. That was a wrong assumption!
I will reseach this and try to to fix it. Would you be willing to help me with testing?

**Comment by Revenrof** [comment]
Absolutely sir ☺

**Comment by IngoZenz** [comment]
woul
[app-debug.zip](https://github.com/IngoZenz/personaldnsfilter/files/2345321/app-debug.zip)
d be great to get feedback for the attached experimental build. 
Please paste the log output after start.

**Comment by Revenrof** [comment]
Debug version work.

Which "log output" should I post here?
Is it the one inside "trafficlog" folder.

Or this : "SUCCESS! EXECUTED SU, iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-port 5300!
Using Blocking Mode!".

How could I test "dnsProxyOnAndroid" feature?

**Comment by IngoZenz** [comment]
Good!
I would need the output of the log UI inside the app...
In order to test it, you could use e.g. a PC in your home network and configure the IP of your mobile, running the dns filter,  as DNS server. The PC should then use the dnsfilter as DNS server.

**Comment by Revenrof** [comment]
Here is the log output :

Initializing ...
***Initializing PersonalDNSFilter Version 1.50.24-EXPERIMENTAL!***
Detecting DNS Servers...
DNS:208.67.222.222
DNS:208.67.220.220
Using updated DNS Servers!



SUCCESS! EXECUTED SU, iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-port 5300!
Using Blocking Mode!
VPN Connected!
Received Network Connection Event: android.net.conn.CONNECTIVITY_CHANGE
DNS Filter: Next filter reload:Mon Sep 10 23:20:14 GMT+07:00 2018
DNSFilterProxy running om port 5300!
VPN Runner Thread started!
!!!IPV6 Packet!!! Protocol:0
!!!IPV6 Packet!!! Protocol:0

**Comment by IngoZenz** [comment]
Looks good!
I also just tested on a rooted Android 6 phone and I was able to use this phone as DNS Server from other devices. You should also select the option to avoid device sleep in order to keep it running for testing.
I will submit the fix as part of the new version. 
Thanks a lot for your help and feedback!

**Comment by IngoZenz** [comment]
Issue is fixed in 1.50.24
