### ISSUE TITLE
Feature request: Add greylisting

### ISSUE THREAD

**Issue by ofiala-a51** [IngoZenz/personaldnsfilter#80]
Allow apps to be greylisted. The connection would still go through DNS filter and thus features such as CNAME Cloaking Protection could still be used, but otherwise the domain blocking rules wouldn't apply. This feature could be further enhanced by implementing app-specific rules.

**Comment by ofiala-a51** [comment]
Workaround for issue #70

**Comment by IngoZenz** [comment]
Sorry - but that's again technically not possible without native and platform dependent coding. Android does not provide any API features to find out the application accessing the network.
