### ISSUE TITLE
Problems with jitsi meet.

### ISSUE THREAD

**Issue by em230418** [IngoZenz/personaldnsfilter#82]
Reference: https://github.com/jitsi/jitsi-meet/issues/6218#issuecomment-617045086

**Comment by afonari** [comment]
Can this be related to the UDP tunneling?

**Comment by em230418** [comment]
> Can this be related to the UDP tunneling?

As @saghul says in https://github.com/jitsi/jitsi-meet/issues/6218#issuecomment-617045086 - maybe yes.

**Comment by IngoZenz** [comment]
I have no idea - in case this is related to a blocked host, try whitelisting the host. Otherwise you need to whitelist the app...

**Comment by IngoZenz** [comment]
is the issue solved? If not, I suggest discussing this in our tg group...

**Comment by IngoZenz** [comment]
Closing as there was no further update
