### ISSUE TITLE
Ad domains (in hosts files) are resolved using dns

### ISSUE THREAD

**Issue by gkrishnaks** [IngoZenz/personaldnsfilter#83]
Hi
Ad resources from domains like ad.doubleclick.net and google-analytics .com and other ad domains are still resolved though I see x mark/red font in the logs view.

I observed this by monitoring the DNS-Over-Https logs tagged to the app. I expect that the domain names shouldn't even be resolved if hosts based filtering is working and it should just simply return (without resolving) either nxdomain or 0.0. 0.0  whichever method is preferred to return ad domains. 

Steps to reproduce:
Look at DNS over Https logs to see resolved domains. 
Observe that even a domain marked with red font and x mark on the app logs are still resolved in Dns over https logs.

**Comment by IngoZenz** [comment]
this is as it works in pDNSf. It requests the DNS server and changes the IP to 127.0.0.1 in case the host or a CNAME is in the filterlist.
I think for protecting from CNAME cloaking, it is needed to resolve in order to also get the CNAME redirects.

**Comment by gkrishnaks** [comment]
Thank you for clarification.
I think it would be more efficient to do the following order : 
1) check if domain is in blocked hosts. If yes, return nxdomain or 0.0.0.0 or preferred value immediately. 
2) resolve domain using upstream dns for what's not blocked by local hosts domains. 
3) check if cname is in blocked list, return nxdomain or 0
4) else return actual address received from upstream dns.

**Comment by IngoZenz** [comment]
I agree that returning 0.0.0.0 for filtered hosts / cnames is better - I will consider this with 1 of the next releases.
For the rest you are right as well, but currently I do not plan to do so because of limitted time and the logic "as is" is working well ...

**Comment by cobratbq** [comment]
I would love to see returned ip changed to `0.0.0.0`, as `127.0.0.1` might accidentally point to some server running locally.

**Comment by IngoZenz** [comment]
Yes...that's on my list

**Comment by sathish804** [comment]
Its better to have the configurable option for these 2 IP addresses.

**Comment by IngoZenz** [comment]
I plan to have this as a configuration within the dnsfilter.conf file

**Comment by BlackDex** [comment]
Could this explain why some domains are not blocked?
I also have a pi-hole running at home, which catches the rest of the requests and then blocks them in the end.
But when I am on mobile-data this doesn't work and they get slipped through.

**Comment by IngoZenz** [comment]
I do not think so.
Most likely this is related to the filter lists you are using...

**Comment by BlackDex** [comment]
I don't think that is the case.
I just double checked and all the filters are configured both on my pihole and my android phone.
Also, shouldn't the option `detectDNS = false` and `fallbackDNS = 9.9.9.9::53::UDP ;149.112.112.112::53::UDP` forward the requests to those resolvers? If that was the case, the shouldn't even show up in my PiHole.

**Comment by BlackDex** [comment]
I just tried the exact same lists with blokada to see if it has something to do with that.
But blokada seems to block them, and i do not see the requests at my pihole either.

Is there something i can do to debug this a bit better?

**Comment by IngoZenz** [comment]
it is getting a bit confused now ... we are mixing 3 issues here:

1. Pdnsf sends request to upstream DNS, even for filtered hosts

==> - This was clarified above - I just want to keep this thread open in order to not forget to make the IP for filtered hosts configurable.

2. Pdnsf sends resolve requests to other DNS Server then the configured one (e.g. your pi-hole)
==> That can't be the case! Looks like config issue. Feel free to discuss this in the TG group

3. Pdnsf does not filter hosts but they are  in the host filters.
==> Please check for such host names and verfify that they are really in the host filter and NOT whitelisted (give examples). This is also s.th. you could discuss in the TG group.

**Comment by BlackDex** [comment]
@IngoZenz I'm sorry to have cluttered this issue.
Apparently i had marked an app to be whitelisted which caused this.

**Comment by IngoZenz** [comment]
No problem - Thanks for clarification :-)

**Comment by IngoZenz** [comment]
Filtered IP is now configurable.
https://github.com/IngoZenz/personaldnsfilter/releases/tag/1.50.41.0
