### ISSUE TITLE
New hosts-file.net block lists?

### ISSUE THREAD

**Issue by jpyper** [IngoZenz/personaldnsfilter#84]
All filters from https://hosts-file.net/ are no longer available.

When connecting directly to the URL like https://hosts-file.net/ad_servers.txt results in a 404 Not Found.

When connecting directly to the main URL https://hosts-file.net/ I get redirected to https://www.malwarebytes.com/browserguard , a page for a browser extension.

Are there any good replacements available?

**Comment by IngoZenz** [comment]
I know...the latest pdnsf version comes with new default filters (Steven Black) and hosts-file.net is removed. You might need to restore default config in backup and restore...
