### ISSUE TITLE
No Internet when connecting to Wi-Fi while pDNSf is running

### ISSUE THREAD

**Issue by S-a-l-a-d** [IngoZenz/personaldnsfilter#85]
It just keeps sending request to connectivitycheck.gstatic.com and www.google.com and the network is reported as No Internet although the requests are green.

Device: Pixel 3 XL
Android: 10
pDNSf configuration: Root Mode (doesn't happen with local VPN mode)

![Screenshot_20200518-023858](https://user-images.githubusercontent.com/5486625/82158289-15c3ac80-98b1-11ea-816a-9b7b263d3c79.png)

**Comment by IngoZenz** [comment]
Would it be possible for you to ask this in our telegram group?

**Comment by IngoZenz** [comment]
is this issue only with wifi? Working with LTE?
Or is it when switching networks?

**Comment by S-a-l-a-d** [comment]
It only happens when switching from LTE to Wi-Fi.
I tried LTE or Wi-Fi alone and it works.

**Comment by IngoZenz** [comment]
ah ok - could you post  the log screen shot after switching from LTE to WIFI?
Could you check the IP Address assigned in WiFi and post it here?

**Comment by S-a-l-a-d** [comment]
There are just regular requests like the screenshot above when switching network.
The IP address is also assigned correctly.

![Screenshot_20200524-142800](https://user-images.githubusercontent.com/5486625/82748330-34eb9e00-9dcb-11ea-8603-279ed9695b35.png)

**Comment by IngoZenz** [comment]
When switching network it should run some iptables command to update routings.
Isn' t it in the log when switching?

**Comment by S-a-l-a-d** [comment]
> When switching network it should run some iptables command to update routings. Isn' t it in the log when switching?
No, there isn't.

**Comment by high1** [comment]
I'm experiencing this also, and it happens only if Disable DNS server discovery is enabled.

**Comment by IngoZenz** [comment]
@high1 Looks like a different issue not related to root mode.
You might create another issue fo rthis and post the log output.
Most likely the "Fallback" DNS server is wrongly configured.

**Comment by high1** [comment]
The device actually is in the root mode, to avoid VPN.

**Comment by IngoZenz** [comment]
ok - can you post the log output when you have the issue?

**Comment by IngoZenz** [comment]
The issue with root mode is fixed in 1.50.46 version - so I close this ticket.
