### ISSUE TITLE
ERROR loading filter: https://raw.githubusercontent.com

### ISSUE THREAD

**Issue by drongkol** [IngoZenz/personaldnsfilter#86]
raw.githubusercontent.com filter can not be load😥

![Screenshot_20200522-014109](https://user-images.githubusercontent.com/65730585/82589260-719e7600-9bce-11ea-9e77-8fa6241c9ac8.png)

**Comment by sequielo** [comment]
@drongkol Apparently, guys from Energized.pro had changed their links.

You should manually edit them with:

    https://block.energized.pro/<PACK>/formats/hosts

where `<PACK>` is the pack name you wish.

**Comment by drongkol** [comment]
Solved. Thanks @sequielo 😊

**Comment by IngoZenz** [comment]
URLs are updated in last release 1.50.40.0

**Comment by stevenfang1997** [comment]
I'm on Fdroid 1.50.40.0 version, but I saw my energized protection URLs are still not updated.

**Comment by IngoZenz** [comment]
You need to restore default config in backup and restore adv settings

>

**Comment by stevenfang1997** [comment]
Thanks for your reply. Problem solved.
