### ISSUE TITLE
Custom DOH endpoint not working

### ISSUE THREAD

**Issue by ciokan** [IngoZenz/personaldnsfilter#87]
I have added `198.211.105.28::443::DOH::https://d273.dns.dnsadblock.com/v5j4h6li` as a manual DNS server but it fails to resolve via this server. It uses the one on the wi-fi router. Is this by design?

**Comment by IngoZenz** [comment]
Most likely you just missed to check the option for deactivation of dns detection

**Comment by ciokan** [comment]
You mean the Disable DNS server discovery? It's checked...

**Comment by IngoZenz** [comment]
In this case you might have missed a restart?
