### ISSUE TITLE
[Bug] Wasting of lines when add domain to blacklist

### ISSUE THREAD

**Issue by ukroplus** [IngoZenz/personaldnsfilter#88]
Hello
Problem is related to subject of my issue.
There can't add domain in one row for completely block (with all subdomains), because add it twice is too double.
```
E.g. only in 1 row root domain still can't blocked
*.daniil.it

For blocking it, need to be as (can see it on second picture below...)
*.daniil.it
daniil.it
```

Some screenshots for example:

>![IMG_20200611_065922](https://user-images.githubusercontent.com/34206921/84343814-e3585700-abb1-11ea-9621-0a2dd413cacf.jpg)
Root domain don't block already.

> ![IMG_20200611_070351](https://user-images.githubusercontent.com/34206921/84343858-fbc87180-abb1-11ea-8861-fcff3a53fb81.jpg)
Confirmed on Motorola One phone with running official Android 10.

But, maybe it caused by _difference of hash_ between a subdomain and root domain?

**Comment by IngoZenz** [comment]
in case you wanto to block daniil.it with all subdomains, you need to add just `daniil.it`
Please restart app after such change.

*.daniil.it will only block subdomains

**Comment by ukroplus** [comment]
Yeap, for further pDNSf tool is working excellent. Now got it. Never mind, it had my blame. Thanks you for reply!
