### ISSUE TITLE
Support for blocking certain URLs

### ISSUE THREAD

**Issue by d-adi4** [IngoZenz/personaldnsfilter#9]
Dear Dev,
This is the best ad blocker for android so far which is lightweight plus powerful.
And I've a request to made, may you add feature of blocking URLs too?
It is needed when user don't want to block whole website but want only to block certain page of that website.
Example: I wanna block www.block.com/block/ but don't wanna block whole www.block.com

**Comment by d-adi4** [comment]
I've checked that out too though couldn't figure out how to use that... But right now I'm on PDF and its far better than anything else.. And even after months I couldn't be able to use "routeips" and "dnsproxy" feature in PDF... So PDF is still advanced to me.. Waiting for your updates..

Sincerely

**Comment by IngoZenz** [comment]
In fact routeips and dnsproxy features are advanced and most people do not need this.
The feature "routeips" can be used in case an app uses hardcoded DNS servers and thus would bypass pDNSf - in such a case you could configure the hardcoded DNS IP to go via pDNSf.
The "dnsproxy" feature requires root and can be used in case you want to run your own dns server (proxy) for filtering not only locally on the device but potentially in your entire network,
Btw: Thw feature you requested would also require a rooted phone and it would not work for https. I do not think I will implement this.
Without root im would require to intercept the wholen etwork traffic and this would make pDNSf pretty heavyweight...
PersonalHttpProxy allows to configure a filterurls.txt file but you need to configure your device to use the httpproxy (per network). However here as well for https you also can only block the whole host.

**Comment by d-adi4** [comment]
Thanks for explaining, now I can use routeips in some good way and for dnsproxy, I still don't know how to use that but I always keep it on anyway cause I'm rooted.
But the best part of PDF is that it is powerful and rooted and non-rooted both users can use this.
And I understand the issue adding that feature would make it heavy, there is "privoxy" which does the same on android without any root though I couldn't even able to set up this too.

**Comment by d-adi4** [comment]
I've used personal http filter and it is working only on certain port.. How to change its port dynamically or set range of ports? Cause on mobile data ports keep changing..

**Comment by d-adi4** [comment]
And with all your due permission, I can start a channel or supporting manual to use PDF and proxy so that users can use both apps at it's full.. If you grant permission.. 
Though, you'll get a lot requests and bug report too.. Hope you'd be glad with that 😅

**Comment by d-adi4** [comment]
OK thanks for giving approval.. Soon I'll share telegram link with you for support of both apps

**Comment by ryder203** [comment]
Any news regarding the Telegram groups?

**Comment by d-adi4** [comment]
No.. Busy in exams.. Will do it soon after exams and let eveyone know here..

**Comment by IngoZenz** [comment]
For URL blocking you can use personalhttpproxy.
I am closing this issue
