### ISSUE TITLE
Checkboxes look like radio buttons

### ISSUE THREAD

**Issue by alexanderadam** [IngoZenz/personaldnsfilter#93]
It might be a detail but it really confused me. The screen looks like I can either chose to have `Advanced settings`, `Enable blocking` or `Autostart`:

![Screenshot_20200707-082351_DNSfilter](https://user-images.githubusercontent.com/372620/86727037-5e832080-c02b-11ea-92fb-083759e0d0fe.png)

The same visual issue exists in the filter list and the `Active` fields when adding a new filter list.

[Here's a blog post on this topic](https://www.justinmind.com/blog/checkboxes-or-radio-buttons-let-the-ui-design-battle-commence/#the-checkbox) in case you're wondering.

It is in general not trivial to understand the UI/UX. I'm not expecting a UI like [blokada](https://blokada.org/#fullscreen) but it really is not clear what thing opens another screen or when content is suddenly hidden/shown.

**PS:** Thank you for your work! :pray:

**Comment by IngoZenz** [comment]
fixed by @memiks
