### ISSUE TITLE
Use configured DNS for resolving hosts to refresh enabled blocklists

### ISSUE THREAD

**Issue by cobratbq** [IngoZenz/personaldnsfilter#99]
PersonalDNSFilter allows configuring specific DNS service (DNS, DoT, DoH) and disabling the DNS servers announced on the network. However, it does not use the configured DNS service when resolving the hosts for downloading/updating blocklists.

PersonalDNSFilter v15.0.51.00,
DNS-over-HTTP configured.

**Comment by IngoZenz** [comment]
![image](https://user-images.githubusercontent.com/11963504/88923179-9455a680-d271-11ea-85d3-82e1f7d54d15.png)
Maybe this can be removed - will check

**Comment by cobratbq** [comment]
Ah right, I can imagine that becoming an issue. Maybe it is possible to resolve the host manually, i.e. first manually resolve the host, then establish a connection to the IP address, so no further resolution is required?

**Comment by IngoZenz** [comment]
I will try to improve with next version ...

**Comment by IngoZenz** [comment]
this is fixed in latest release 1.50.42.03
